### ISSUE TITLE
Fix issues with emails and make them more helpful

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1006]
**[Sylvain edit: updated requirements are in [this comment](https://github.com/Metaculus/metaculus/issues/1006#issue-2589176841) below.]**

* Notebooks like this one are being shown in the "other questions you may be interested in section" https://www.metaculus.com/notebooks/12294/a-public-prediction-by-ai-impacts-expert-survey/
* It would be much more useful if emails had different subjects depending on what they are
    * Notifications about new comments on questions for which I've clicked follow show up grouped in the same email as questions where I get tagged. This makes it hard to categorize at a glance, and impossible to set up email filters intelligently.
    * Similarly, would be really nice to get separate admin and moderator tag subject lines. Especially since comments are truncated now in the email, so you can't tell at a glance from the email what the reason you're getting notified is (sometimes people put admin tags or moderator tags at the end of a comment instead of the beginning).
        * Not batching mod and admin emails would be helpful for me personally as well, for inbox tagging and to-dos, though this should probably be low priority if it's not easy.
    * Also this may just be personal preference on my part, but I'd ideally like admin and moderator tags to not be truncated in the email, so I can assess them without having to click through. Really slows down my workflow to have to click through on many of them for full context.
    * Email subject lines that would be good to change:
        * When you follow a tournament the subject line you get is "questions have changed status". You should only get an email notification when a question is set either to upcoming from pending or to open from pending, and the subject should say "New questions have opened in [project name]". See here: https://github.com/Metaculus/metaculus/issues/1086
        * Ideal subject line when someone tags your username: "[User] has mentioned you in a comment". See here: https://github.com/Metaculus/metaculus/issues/1170
        * @ moderators should give a subject line like: "[User] tagged moderators in a comment"
        * Similarly @ admins should give a subject line like: "[User] tagged admins in a comment"
        * For questions you've requested notifications for new comments on subject should say: "Question has new comments: [question title]"
        * Maybe a special subject line for @ predictors tags?
        * **However**, the above is my opinion and to some extent breaks batching for most things except for question resolutions. To me this is preferable as it makes my inbox much more manageable and clear, and allows filtering and automatic organizing. But might be worth taking a pulse check of other power users for if they think the inbox experience is better or worse.
* Can we get rid of the "other questions you may be interested in", or at the very least make it more compact? I've attached a printout of what this looks like in my inbox, Gmail helpfully groups emails with the same subject together, but the addition of this section means I have to scroll forever to find the actual comments I clicked on the email grouping for. If nothing else, would be great to separate out admin and moderator tags and not include suggested questions on those in particular. But in general I think the suggest other questions section isn't useful for comment notifications, that's useful for questions that have resolved where someone might have only dabbled on the platform and might not come back otherwise, but in my view doesn't help anything for someone getting tagged in a comment. If you're getting tagged in a comment it means you've probably already commented on something and are therefore engaging in conversation already.
* Notification related emails should be sent from notifications address instead of accounts address. https://github.com/Metaculus/metaculus/issues/969

[Gmail - Questions have new comments.pdf](https://github.com/user-attachments/files/17381149/Gmail.-.Questions.have.new.comments.pdf)

**Comment by hlbmtc** [comment]
cc @SylvainChevalier

**Comment by ryooan** [comment]
Related: https://github.com/Metaculus/metaculus/issues/1170

**Comment by ryooan** [comment]
Also this one is related, I'm adding it to the text above and suggest closing the one linked here: https://github.com/Metaculus/metaculus/issues/1086

**Comment by ryooan** [comment]
Ditto this one about the address it comes from: https://github.com/Metaculus/metaculus/issues/969

I suggest just making this a master "make emails much nicer" issue and lumping all these into here, thoughts @SylvainChevalier? This is marked as one of my time sinks because currently I think the email experience isn't great and slows me down, I suspect also not great for other power users, though am unsure on that part.

**Comment by SylvainChevalier** [comment]
Copied from [spec](https://www.notion.so/metaculus/email-fixes-1446aaf4f10180cba9e9d132dfccc407):

### emails are sent from `notifications@mg2.metaculus.com`

and not `accounts@mg2.metaculus.com`

### `@mentions` send emails instantly

copy:

> Subject: {username} mentioned {you, admins, moderators, predictors} on “{question title}”

>Hello {username},
>
>{username} mentioned {you, admins, moderators, predictors} on [[question title](https://>github.com/Metaculus/metaculus/issues/url)](url):
> {comment text}

(Note the absence of the “questions you may be interested in” section.)

### all other email types are batched 2× per day

Currently they're every hour, but only the mentions need to be fast, so we can lower frequency of all other. This will also increase batching.

### “other emails that may interest you” are switched to a 2×2 grid

![image](https://github.com/user-attachments/assets/20e3e29c-a639-4cd6-aa20-001cf71e5ca0)
