### ISSUE TITLE
Conditional where child resolved before parent isn't closed

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1008]
This conditional had the child resolve before the parent: https://www.metaculus.com/questions/22051/starship-booster-tower-catch-attempt-in-2024/

It doesn't show any indication that that's the case. It also still allows users to input forecasts, though does not save the forecast upon submitting it.

My understanding is that if the child closes or resolves before the parent, the conditional should update to show that the question is closed and no longer accept forecasts, and then it will be scored once both the parent has resolved and the child has resolved.

**Comment by SylvainChevalier** [comment]
We should also display some explanatory text when the parent xor the child is closed/resolved.

Child closed, parent open:

> The question <b>"{child short title}"</b> has closed, so these conditionals are closed for forecasting. They will resolve when the question <b>"{parent short title}"</b> resolves.

Parent closed, child open:

> The question <b>"{parent short title}"</b> has closed, so these conditionals are closed for forecasting. They will resolve when the question <b>"{child short title}"</b> resolves.

**Comment by ryooan** [comment]
@SylvainChevalier I think we should bump this one up to high priority, it's confusing to users because it still accepts forecasts but should have closed a while ago.
