### ISSUE TITLE
Writing Medal contributions page loading error and awarded medal inconsistencies

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1009]
User Zaldath mentioned in [this comment](https://www.metaculus.com/notebooks/28734/a-massive-rewrite-a-slate-of-improvements-and-going-open-source/#comment-200216) that their previously awarded question writing medal no longer exists (after the open source transition specifically). 

The [relevant contributions page](https://www.metaculus.com/contributions/?category=questionWriting&user=139161&year=2023&duration=1) is not loading properly, which needs to be fixed and possibly could help describe the difference. [Here is the prior version for reference](https://old.metaculus.com/contributions/?category=questionWriting&u=eNqLSsxJSSzJAAAK4gLJ&year=2023&duration=1).

TODO:
- [x] the contributions page loading error needs to be fixed
- [x] change in algorithm must be determined
- [x]  if change is in error, fix.
- [x] If change is not in error, provide proper justification for change and decide policy on previously awarded medals

**Comment by lsabor** [comment]
My initial suspicion for the medal not being awarded is that fewer total competitors are being considered for placement on the leaderboard rather than the math which calculates the user's H-index being different. This is not well documented, but I think that the new algorithm is better justified than the old. The exact difference requires investigation, though.

If the new algorithm is indeed more justified, a policy decision will be required about whether to manually award prior medals that wouldn't have been awarded by the new algorithm.

**Comment by lsabor** [comment]
Update on this. The old algorithm has multiple bugs.
1. questions that are closed before the leaderboard start still count, just have a score of 0 meaning that the author got registered on the leaderboard even though they may not have had any authored questions open during the leaderboard period.
2. All Question types (old concept of question) were included like Notebook and Public Figure. Of course there were no forecasts on those, so they always got a score of 0, but some individuals had published notebooks only which registered them in the leaderboard inappropriately
3. the total number of registered competitors (against which the 5% medalists are calculated) included excluded entries like staff. This also inflated the numbers.

Two errors in the rewrite:
1. Not all coauthors were migrated properly. For instance: Joker (114911) should be coauthor of the group question https://www.metaculus.com/question/17299/ This doesn't seem to have a major effect other than specific rankings of effected individuals (Joker has a placement of 10 on the 2023 leaderboard instead of 7th.
2. Users that wrote questions while staff should be excluded from getting awarded for participation on those questions even after they are no longer staff. This includes Tamay who erronerously has a high ranking on the 2023 leaderboard while they shouldn't even be on the leaderboard at all (all questions were authored while they were staff). This takes a medal place away from someone who deserves it.


I have noted to Hlib to fix the coauthorship bug.
I'll fix bug 2 for the rewrite.

The errors from the old site are now corrected, but rather than reproducing them, product needs to decide whether to manually award the previously erroneously awarded medals or overwrite them with the new algorithm.

**Comment by lsabor** [comment]
Fix for rewrite 2 is now merged. I'll need to wait for 1 and product decision in order to continue.

**Comment by hickman-santini** [comment]
Thanks for the detective work here @lsabor.

On reflection I don't think we should set a precedent for taking away people's medals when we discover bugs post hoc. If users get medals in the rewrite that they _didn't_ have before, that's totally fine. But I'd like to manually award Zaldath their medal back (and anyone else who had a medal before, if that's easy enough to find out).

Let's let @SylvainChevalier weigh in, but if he agrees, can you generate the diff between people with medals post- and pre-rewrite? Or if that's sufficiently hard, we can be reactive and just award Zaldath their 2023 question writing bronze medal for now.

**Comment by SylvainChevalier** [comment]
@hickman-santini the precedent has already been set, we've fixed some medal bugs in the past. More importantly, the cost of maintaining an exception forever is imo higher than the cost of apologising to the few users who're going to notice. I would 100% not retroactively change the _rules_ of how medals are awarded (which is why the peer leaderboards use different maths for <2024 and >2024), but fixing bugs is different.

**Comment by hickman-santini** [comment]
Ok yeah that makes sense.

>  product needs to decide whether to manually award the previously erroneously awarded medals or overwrite them with the new algorithm.

@lsabor go forth and overwrite! I'll respond to Zaldath.

**Comment by lsabor** [comment]
Thanks for the swift decision! :)
I will do thy bidding.

**Comment by lsabor** [comment]
fixed error 1 manually

I've recalculated the writing leaderboards, Closing as complete.
