### ISSUE TITLE
Multiple choice questions are showing the CP extending beyond the resolution in the feed

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1016]
See the picture below, in the feed multiple choice questions that resolve are showing a CP history beyond the resolution date, when it should stop at the resolution date.

![image](https://github.com/user-attachments/assets/b973b3f9-d834-4283-81ed-0250760c4b57)

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
LGTM on prod
![image](https://github.com/user-attachments/assets/e23a1a24-4ac6-4702-b9cf-baca312979f9)
