### ISSUE TITLE
Multiple choice aggregate not being normalized to sum to 100%

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1017]
After the rewite the CP on this multiple choice question no longer sums to 100%, it's been as low as around 93.5% total in the past week as of posting it. https://www.metaculus.com/questions/22303/additional-human-bird-flu-cases-in-us-2024/

![image](https://github.com/user-attachments/assets/5726c00a-b51a-4e40-84e0-032067e3248a)

**Comment by lsabor** [comment]
Thanks for spotting this.
Closing as complete.

**Comment by lsabor** [comment]
for the record, the issue was introduced last week because I failed to QA a PR well enough.
This is a better fix than before the bug was introduced though.
