### ISSUE TITLE
Project tags not showing on some questions

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1018]
Seems like none of the questions in the [Forecast With GiveWell](https://www.metaculus.com/tournament/forecast-with-givewell/?status=pending) project are showing the project tag on the page. 

Example: https://www.metaculus.com/questions/28395/will-who-prequalify-moxidectin-by-2027/
 
![image](https://github.com/user-attachments/assets/a37e1469-55a3-4997-a65b-67cfef0e1f79)

**Comment by SylvainChevalier** [comment]
@ryooan that question is not in the project.

**Comment by ryooan** [comment]
@SylvainChevalier it is, or at least should be. Shows up here like it should: https://www.metaculus.com/tournament/forecast-with-givewell/

**Comment by ryooan** [comment]
Also says it is when you click edit

**Comment by ryooan** [comment]
I just set it public and see them now. Maybe the issue is that project tags aren't showing on private questions?

**Comment by SylvainChevalier** [comment]
I think private project tags aren't shown on questions. Making a new issue.

**Comment by SylvainChevalier** [comment]
https://github.com/Metaculus/metaculus/issues/1126
