### ISSUE TITLE
2 years leaderboards inconsistencies

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1021]
Apparently a question finally resolved in the 2024-2025 timeline but I have found it weird.

The forecasters are not the same in the baseline and the peer ranking. I guess negative scores are not displayed but Is there a way that some forecasters would have a positive peer but negative baseline?? That seems counterintuitive considering how things usually end up.
I am in the peer leaderboard but not in the baseline one and I have not received a notification for a question related to this timeline so this looks very weird.

The scores are also shown with the e exponent in the peer leaderboard.

**Comment by draaglom** [comment]
> I guess negative scores are not displayed but Is there a way that some forecasters would have a positive peer but negative baseline??

That appears to be exactly what has happened. Clicking into the people showing on the 2024-2025 peer leaderboard, this is the only resolved question:

https://www.metaculus.com/questions/27800/

The community aggregate was well under 50% for most of the question duration and ultimately resolved yes, so it seems plausible that nobody got a positive baseline score.

**Comment by exmateriae** [comment]
I did not remember that the closing date was superseeding the resolution date even when it was resolving in the year during which the question opened! 
Thanks, I thought it was so unlikely that only 7 forecasters scored any point in any category at all that it looked like a bug but indeed that was the case...

**Comment by SylvainChevalier** [comment]
Thank you both for looking into it. Closing.
