### ISSUE TITLE
No second click required to unresolve a question

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1034]
![image](https://github.com/user-attachments/assets/95dae5b7-ef11-4d5e-8231-7c4921d4d5a0)
Currently, if an admin accidentally clicks "Unresolve", it just does that action. I'd prefer if at least a modal pops up that said "Are you sure?"
Probably should be something nicer than that, but unresolving should require 2 clicks at minimum for safety.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
I want this to say "Are you sure you want to unresolve this question?" Button: "Yes"
![image](https://github.com/user-attachments/assets/1302d635-11e6-4f3b-851d-38c40836142b)

@ncarazon

**Comment by ncarazon** [comment]
Sure, I will fix that

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
:tada:
