### ISSUE TITLE
When CP is hidden, populate timeline graph with user's predictions

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1041]
>when viewing a question in the Questions view with its community prediction still hidden, I can only see this text:
“Forecast data is empty”
(Even though I used to be able to see my own prediction in that scenario)

Apologies if this is a dupe of another issue.

**Comment by nangchrys** [comment]
Already mentioned [here](https://github.com/Metaculus/metaculus/issues/937).

**Comment by ncarazon** [comment]
Closing as duplicate. Will focus on the original issue
