### ISSUE TITLE
Bring back "oldest predictions first" filter 

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1049]
It is now impossible to access your oldest predictions easily which is a big issue for people who forecast on thousands of questions.

**Comment by lsabor** [comment]
additional notes from Bruno Parga:
>There doesn't seem to be a way for me to get either my open or my newest personal predictions. When I have the Personal filter selected, I don't see the Open filter – this is another instance of what I reported above, of some other circumstance removing that filter from view. Also, when I click on the "More" dropdown and select Newest, that removes the Personal filter.
And I am getting non-personal authored questions shown with the Personal filter applied (screenshot).

**Comment by exmateriae** [comment]
I found out that this still works in tournaments.

**Comment by lsabor** [comment]
@exmateriae I don't see the way to make it happen inside tournaments. Can you document what you've found?

**Comment by exmateriae** [comment]
> @exmateriae I don't see the way to make it happen inside tournaments. Can you document what you've found?

I went to tournaments, chose the current quarterly cup and among the first type of filters you should be able to choose by oldest prediction date.

**Comment by lsabor** [comment]
Ahh, there is some level of inconsistency about when / which filters are available. The filters all exist. If you are in urgent need of the filter, at any point where you have a feed you can add `?forecaster_id=<your user id>&order_by=-user_last_forecasts_date` to get the results ordered by most recently forecasted first and `?forecaster_id=<your user id>&order_by=user_last_forecasts_date` by oldest first.

**Comment by lsabor** [comment]
@ncarazon Can I pass this off to you? The filter to order by "user_last_forecasts_date" should be available whenever a user is logged in. I haven't looked into it too closely but it looks like there is inconsistency.

**Comment by ncarazon** [comment]
Sure, I’ll take a look after handling the high-priority tickets

**Comment by SylvainChevalier** [comment]
This is what the "stale" filter is for, see https://github.com/Metaculus/metaculus/issues/948, I've upped the priority there.
