### ISSUE TITLE
Group options not updating on the timeline

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1052]
Sorry if this is already an issue but I did not find it.

On groups, when you update only one of the options, the ones you do not update show a ? when looking in the timeline. This is very annoying because you have to update everything everytime to be able to have a good look on your forecasts.

**Comment by SylvainChevalier** [comment]
Sorry, I'm not sure I follow. Could you provide a screenshot that showcases the problem?

**Comment by exmateriae** [comment]
![image](https://github.com/user-attachments/assets/20312feb-4108-4ba1-853e-4a8b63426272)

**Comment by exmateriae** [comment]
Great thanks!
