### ISSUE TITLE
Problems when adding a subquestion to an existing question group

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1058]
I'm currently experiencing several problems when trying to add a subquestion to an existing question group:

1. No open date or CP reveal time shown when adding a subquestion to an existing group question

Currently when I try to add a subquestion to an existing group question no option is shown for open date or CP reveal time. I'm able to add the subquestion, but I can't forecast on it, I think because the open date isn't set. In admin it looks like the open date field is blank.

2. After setting the open date in admin, it's showing a resolution diamond in the table next to it instead of a question mark or a CP

![image](https://github.com/user-attachments/assets/4242f238-3747-4a22-a7ed-f304fa9b0788)

I also just set the CP reveal time 5 minutes in the future, and that hasn't removed the diamond, and after the CP reveal time passed it also did not change the diamond.

Here's the question I experienced the above issues on: https://www.metaculus.com/questions/28378/ with the "Nebraska (Class I)" subquestion being the one I added.

**Comment by hlbmtc** [comment]
@ryooan I've just fixed the diamond behaviour, so you can publish newly created subgroup questions manually from the admin panel, so you're unblocked now

**Comment by hlbmtc** [comment]
I'll add UX improvements early next week -- https://github.com/Metaculus/metaculus/pull/1071

**Comment by ryooan** [comment]
@hlbmtc thank you! Will it break anything if I add a question on the front end and then set the close and cp reveal in admin afterwards?

**Comment by ryooan** [comment]
Adding some context / related features from message with @hlbmtc :

Hlib:

>Another question: do you wanna edit cp + open time fields just for newly added questions (right after you clicked “add subquestion” button) OR for all questions within a group?

Ryan: 

> Oh yeah, CP reveal time should be editable on all questions at all times (applies to non groups too). So I'd show it and allow it to be editable for all subquestions.
>
>A couple ideals I think would be worth mentioning too, though totally defer to you on prioritization and feasibility, these are more feature requests, but want to mention in case it synergizes with what you're working on:
>
>* For group questions, it would be ideal to have an option to make the open and CP reveal dates set all at the same time. It's a pain in the approval window to set the open and cp reveal date for every subquestion. It used to be that when you clicked approve on a pending group question you got one open and cp reveal date and it applied that to all subquestions, then you could go in after if any needed to be customized. The most often case is that the open and cp reveal date should all be the same. The cases where that doesn't apply are usually ones like [this](https://www.metaculus.com/questions/19912/us-weekly-ed-visit-share-23-24/), where the group is a container for questions spanning different time periods.
>    * Similarly, when editing could be handy to have an override to change open and cp reveal, or maybe close and resolution dates too, all at once. This is less often needed though. The way I used to hack around this was if I needed to change the open and cp reveal date on a group question that was upcoming, I'd set it back to pending and then reapprove it which would set the open and cp reveal date all at once.
>* Like I mentioned editing the CP reveal date comes up pretty often on all questions, so would be great if that can be shown in the edit view for all questions. Currently CP reveal date isn't shown in the edit window on the front end.
