### ISSUE TITLE
Question group display issue (also impacting high visibility election hub)

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1059]
Currently the CP on the US election question is 50/50, but the hover text is out of date and does not change when I pan over the forecast.

![image](https://github.com/user-attachments/assets/644307ab-074d-4f70-95cb-6e4a45bb4917)

Additionally, the embed no longer shows the latest forecast, you have to hover to see what the actual forecast is. This may have been intentional, though I think there's a major downside to making people have to read a graph instead of being able to see the latest number straightaway.

Old (to be clear the design on this was also not very good, since the graph gets squashed):

![image](https://github.com/user-attachments/assets/71789066-5d4f-4e55-b4dc-4d9eb6f506b4)

New:

![image](https://github.com/user-attachments/assets/12fd69ad-163a-455b-8578-c7e414efe61a)

**Comment by ryooan** [comment]
Possibly related to this as well: https://github.com/Metaculus/metaculus/issues/1060

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
Likewise this one @ryooan (if you could check whether this looks fixed, that would be great)

**Comment by hickman-santini** [comment]
Something new amiss (unrelated?) with feed cards on dev:
![image](https://github.com/user-attachments/assets/d4100c04-193c-4d4c-9c47-1fcf7d738d4b)

@ncarazon

**Comment by hickman-santini** [comment]
LGTM
