### ISSUE TITLE
Group and multiple choice timelines are linear but should be step

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1064]
They use [linear](https://d3js.org/d3-shape/curve#curveLinear) interpolation between points:
![Screenshot_20241018_095118_Firefox Beta](https://github.com/user-attachments/assets/d7c03e67-32d2-4127-a6fb-6d8663fc86ae)

But should be [stepafter](https://d3js.org/d3-shape/curve#curveStepAfter), like binary and continuous questions:
![Screenshot_20241018_095152_Firefox Beta](https://github.com/user-attachments/assets/2b738663-3e2f-4842-b185-cc14119d7e87)

**Comment by ncarazon** [comment]
Ready for testing on prod
