### ISSUE TITLE
Posthog dashboard not receiving data 

### ISSUE THREAD

**Issue by aseckin** [Metaculus/metaculus#1066]
The `metaculus-web` project in Posthog is not being updated with new data.

![image](https://github.com/user-attachments/assets/12036eb6-a66f-4458-bafd-b3da0a8dbb21)

**Comment by ncarazon** [comment]
This was fixed in terms of Communities project.

**Comment by SylvainChevalier** [comment]
@aseckin do you confirm this works now?
