### ISSUE TITLE
Feed rendering errors

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#1067]
## Current behavior
> The main feed on my iPhone 6s using Chrome consistently shows an error. The errors are where the discussion posts are supposed to be. Sometimes the post shows up correctly for 2-3 seconds, then goes to the error message.
Link + video: https://metaculus.slack.com/archives/C01Q9AQBVHB/p1729255090514009

I assume there could be something with regexp of "group of questions". You can try to debug this with browserstack. Ping me if you find this very hard to fix, so we would probably migrate to separate label fields for subquestions

**Comment by ncarazon** [comment]
TODO: add Awaiting QA label once dev deploys are enabled again

**Comment by ncarazon** [comment]
Note: in order to test you have to be on IOS 16.3 or below. The issue was caused by lack of support for specific syntax of regular expression on outdated WebKit version.

**Comment by ncarazon** [comment]
Ready for testing on prod
