### ISSUE TITLE
Improve comment timestamps

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#1068]
## Current behavior
Current timestamps are not informative and it's hard to navigate:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/66ab308a-c766-40e5-a20c-9f3b89fae3b7">

## Expected/desired behavior
<img width="347" alt="image" src="https://github.com/user-attachments/assets/4aef4235-8460-4143-a8de-5b7377285516">

Change to relative labels

**Comment by draaglom** [comment]
I'm happy to tackle this if you'd like @hlbmtc while I'm looking at comment stuff

Any objections to using this dep? https://github.com/github/relative-time-element

I think it's a good option -- supports SSR, localisation, and is consistent with UI users will often be familiar with (ie github)

It looks like a pretty easy change if so

**Comment by hlbmtc** [comment]
@draaglom Yeah, would be great, thanks! @ncarazon do you see any concerns here?

**Comment by ncarazon** [comment]
@draaglom the package you shared doesn’t appear to support JSX, so it may not be the best fit for our project

**Comment by draaglom** [comment]
@ncarazon when you say doesn't appear to support -- what are you looking for specifically? While it's a webcomponent, that's no blocker AFAIK (I tried it for a prototype before commenting and it does indeed work)

**Comment by ncarazon** [comment]
@draaglom sorry, I did a closer look and it looks like it actually can be integrated into react app by providing `IntrinsicElement` type for the element. 

I think it's okay to use this dependency given that is worked fine in your prototype 👍
