### ISSUE TITLE
Resolution date and sometimes scores not showing properly for resolved subquestions

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1088]
**Desired behavior:** When a subquestion (i.e. choice) in a group question is resolved, should show that subquestion's resolution date.

The resolution date and sometimes scores for resolved subquestions don't seem to be showing properly, see the video. I just resolved [this group question](https://www.metaculus.com/questions/19881/which-team-will-win-the-2024-wnba-finals/), using different resolution dates for many of the subquestions, and clicking through it shows below it "October 12, 2024" for all subquestions, though I don't think I used that date for any of them. That's the originally scheduled close date.

Additionally, as I click through, two of the subquestions don't show scores for the community at all.

Note that I did have to un-resolve and re-resolve some of these to enter the right "date resolution was known", which I initially hadn't entered properly. Unclear if that's contributing.

https://github.com/user-attachments/assets/f80fdc03-c0e6-465d-9bde-8df50b1c8902

**Comment by ncarazon** [comment]
The issue with resolution dates is ready for testing on dev.

Regarding the second one, it seems to be BE-related, as there is no data returned in the aggregation array, which results in missing scores section. @lsabor would you have a chance to take a look?

**Comment by lsabor** [comment]
Fixed manually! Just had to re-score them.
Closing accordingly
