### ISSUE TITLE
Delete the public figures and public figure predictions

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1095]
## Current behavior
Public prediction notebooks cluttering up searches (reported by Bruno)

![image](https://github.com/user-attachments/assets/b3946f8f-99e9-4bce-ba98-195322edb25e)

Public figures question series clutering up the tournament page.
![image](https://github.com/user-attachments/assets/c4db84c3-dca0-4725-9368-ba7c46614c1d)
You can find all the public figure projects in the old database with:
```
select *
from metac_project_project p
where p.type = 'PF'
```

## Expected/desired behavior
Just remove these altogether.

**Comment by SylvainChevalier** [comment]
(added the public figure question series to molly's comment)

**Comment by hlbmtc** [comment]
@SylvainChevalier removed notebooks and tournaments you mentioned, could you please check again?

**Comment by SylvainChevalier** [comment]
lgtm!
