### ISSUE TITLE
Let people opt out of analytics

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1098]
The cookie banner should let you opt out of analytics cookies.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
1. Could you add a "Necessary only" button to the banner? One less click is nice.
2. I cleared my cookies to test, should we force show the banner to everyone when we merge this, so they have a chance to change their settings if they want to?

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm
