### ISSUE TITLE
Closed questions don't show the aggregate in AI Benchmarking

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1099]
## Current behavior
The CP is not shown on the question below, even though it is closed.
![Screenshot 2024-10-22 at 10 34 59 AM](https://github.com/user-attachments/assets/c216c29d-a3bb-4235-bc24-edd60c84386a)
![Screenshot 2024-10-22 at 10 35 11 AM](https://github.com/user-attachments/assets/7bb6bb7b-ece0-4561-b804-751f45a26a72)

https://www.metaculus.com/questions/29010/on-october-31-2024-will-nvidias-market-capitalization-be-larger-than-apples/

**Comment by Tommetaculus** [comment]
@SylvainChevalier It would be great to have this in a couple days, since right now it is hard to see what the bots are forecasting. But, it definitely can wait a day.

**Comment by ncarazon** [comment]
@lsabor I believe this is a backend-related issue. For every question except [this one](https://www.metaculus.com/questions/28765/practice-on-october-15-2024-will-nvidias-market-capitalization-be-larger-than-apples/), the aggregation field is empty. The same issue persisted in the previous [AI tournament ](https://www.metaculus.com/tournament/aibq3/?) as well. Can you take a look?

**Comment by lsabor** [comment]
Ahhh, it's a rather easy fix and it's on me. I didn't add the `include_bots_in_aggregates` flag into building the aggregations, so it just thinks that there are no forecasts at all. I'll fix it ASAP

**Comment by lsabor** [comment]
closed as complete
