### ISSUE TITLE
Quote markdown in fine print not rendering correctly

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1104]
This
![image](https://github.com/user-attachments/assets/c2727b8a-08d7-4fee-827e-346af43bc4ce)
renders like this (instead of line breaks, no space before "Emissions")
![image](https://github.com/user-attachments/assets/4de05f79-fc8f-47f9-950c-93561c997f60)

May be able to feed two birds with one scone? https://github.com/Metaculus/metaculus/issues/852?

**Comment by SylvainChevalier** [comment]
Duplicate of #1496
