### ISSUE TITLE
Closed question filter includes open questions

### ISSUE THREAD

**Issue by pgodzin** [Metaculus/metaculus#1111]
## Current behavior

Using the question filters to filter on closed questions does not filter out open questions:
https://www.metaculus.com/tournament/aibq4/?forecaster_id=191935&status=closed

![image](https://github.com/user-attachments/assets/4367da2a-3f41-4a65-ad86-2cab14810178)

## Expected/desired behavior

Open questions are not returned

**Comment by lsabor** [comment]
likely connected to #1217 
looking at it now

**Comment by lsabor** [comment]
The stated behavior is no longer the case. I think some open/close filters were fixed in another ticket. Closing as complete.
