### ISSUE TITLE
Comment @ mentions don't work before some punctuation

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1112]
- @Sylvain  works
- @Sylvain. doesn't work
- @(Sylvain). works

See [here](https://dev.metaculus.com/questions/10397/sales-volume-of-20-cultured-meat/#comment-191042)
![image](https://github.com/user-attachments/assets/82d434fc-c89e-4f36-af89-66faf08dbc6f)

**Comment by ryooan** [comment]
Maybe consider upping priority for this if it's quick, tags not going through leads to missed pings for admins as well as friction in site conversations.

**Comment by Sylvain** [comment]
But @sylvain works in Github and it’s me ;)

**Comment by SylvainChevalier** [comment]
@Sylvain oops, my bad. Sorry!

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
LGTM @ncarazon!
