### ISSUE TITLE
Analytics Event Tracking

### ISSUE THREAD

**Issue by aseckin** [Metaculus/metaculus#1116]
We’ve lost the ability to track custom events after the rewrite. I've put together an updated list, along with their Value or Label fields to save when relevant.

[Full list of events to be tracked](https://www.notion.so/metaculus/Analytics-Event-Tracking-1286aaf4f10180d28e38e9ffc5ad775c?pvs=4)

**Comment by ncarazon** [comment]
I've added all the events except for the onboarding one. It should be ready for testing on the dev

**Comment by aseckin** [comment]
@ncarazon is it only the dev environment sending the events to GA4 currently, or is it prod as well? I see most of the events started getting populated already, and they look like prod data but wanted to make sure

**Comment by aseckin** [comment]
This looks good to me, I noticed a few things we're missing but they're not crucial, so we can merge this.

## questionTagClicked
does not contain data for the name of the tag clicked

## postComment
does not contain data for if a prediction is included or not

## questionVoted
does not contain location data for where the voting happened (whether in question page or feed)

**Comment by ncarazon** [comment]
Updated the params passed during event tracking

**Comment by aseckin** [comment]
Perfect - I don't see a label for QA Passed, do we just close the issue now?

**Comment by hickman-santini** [comment]
@ncarazon if this is on prod now, good to close! Thanks
