### ISSUE TITLE
Meta Title and Descriptions

### ISSUE THREAD

**Issue by aseckin** [Metaculus/metaculus#1140]
We're missing meta titles and descriptions for various pages, which currently defaults to 'Metaculus rewrite'. Let's update the default to: `Metaculus is an online forecasting platform and aggregation engine working to improve human reasoning and coordination on topics of global importance.` Let's also update the following pages:

**Page:** /leaderboards/
**Title:** Leaderboards | Metaculus
**Description:** Explore the top forecasters on Metaculus and see how users rank by prediction accuracy and community participation. 

**Page:** /news/
**Title:** News | Metaculus
**Description:** Latest updates in forecasting, featuring expert insights, community highlights, and platform developments. 

**Page:** /about/
**Title:** About Metaculus
**Description:** Metaculus is an online forecasting platform and aggregation engine working to improve human reasoning and coordination on topics of global importance.

**Page:** /tournaments/
**Title:** Tournaments | Metaculus
**Description:** Help the global community tackle complex challenges in Metaculus Tournaments. Prove your forecasting abilities, support impactful policy decisions, and compete for cash prizes.

**Page:** /questions/
**Title:** Question Feed | Metaculus
**Description:** Explore a diverse range of forecasting questions on Metaculus, covering global issues, scientific breakthroughs, and future events.

**Page:** /questions/create/
**Title:** Create a Question | Metaculus
**Description:** Post your own forecasting questions on Metaculus. 

**Page:** /accounts/profile/[slug]
**Title:** [username]'s profile | Metaculus
**Description:** [bio] field for user, if available. If not, use default description.

**Comment by aseckin** [comment]
Forgot to mention the following: 
**Page:** /tournament/[slug]
**Title:** Tournament Name
**Description:** First paragraph of description
same applies to Notebooks:
**Page:** /notebooks/[id]
**Title:** Notebook Title
**Description:** First paragraph of content

**Comment by ncarazon** [comment]
TODO: add Awaiting QA label once dev deploys are enabled again

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
