### ISSUE TITLE
Add on-platform question edit field for 'Include Community Prediction on Date x'

### ISSUE THREAD

**Issue by christianMet** [Metaculus/metaculus#1146]
## Current behavior
Currently, curators for Community pages (and everyone else, but curators are the important constituency here), have an opportunity to set the CP reveal date when they approve questions. However, they cannot later edit this date. 

## Expected/desired behavior
Curators and others able to edit questions should also be able to adjust the CP reveal date on platform. Currently this can only be done in admin.

**Comment by lsabor** [comment]
@ncarazon , can you take this one?

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
