### ISSUE TITLE
"Load more" status is not maintained

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1149]
## Current behavior
On the main feed (or in tournaments), if I "load more" at the bottom I see more questions. If I click into a question, and then click back I return to the main feed - but NOT where I left off. 

This causes considerable wasted time especially in the AI Benchmarking tournament where there are 100s of questions. Use case: I like to explore what the Metaculus bots are forecasting & spot check many questions. But, every time I'm sent back to the beginning and have to scroll down to "load more" click scroll again, click again, scroll again, click again - just to get down to ~50th question. I click into 1 question, then when I return to the feed I have to repeat the entire process above.

## Expected/desired behavior
When I click back from a question detail page, I return to the same place that I left the feed.

**Comment by draaglom** [comment]
this would be very nice!

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by Tommetaculus** [comment]
Works for me! Thank you Nikita!

**Comment by SylvainChevalier** [comment]
@ncarazon this doesn't work for me. (linux, Firefox and Chrome)

Steps:
- Get to `https://www.metaculus.com/questions/`.
- 10 questions are loaded.
- Click load more.
- 10 more questions load.
- Url is now `https://www.metaculus.com/questions/?page=2`.
- Click on 15th question.
- Question loads.
- Click back.
- Url is `https://www.metaculus.com/questions/?page=2` again.
Observed: only 10 questions are loaded, and I'm scrolled all the way down.
Expected: all 20 questions are loaded, and I'm scrolled to the 15th question (or wherever I was scrolled before).

**Comment by ncarazon** [comment]
@SylvainChevalier there was a regression after merging global search feature. Pushed a fix to dev

**Comment by SylvainChevalier** [comment]
Sorry for the lateness. Is this on prod or still on dev?

**Comment by Tommetaculus** [comment]
There are improvements, which are much appreciated on prod.

There are still issues that cause a time sync on prod.

Ex: 
Go to AI Benchmarking: https://www.metaculus.com/tournament/aibq4/
Click load more at the bottom.
Click into a question & then click back button.

At this point, I am returned to the proper place in the feed.

No click into another question at the bottom & hit the back button.

Now it does not return me to the proper place in the feed.

It appears that it only works once reliably.

**Comment by ncarazon** [comment]
Actually, I see another regression after merging a logic to disable automatic search params with global search. Working on a fix

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
