### ISSUE TITLE
"Invalid forecast values" and deleted forecast

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1153]
I was trying to input a prediction in a couple subquestions of [this question](https://www.metaculus.com/questions/29026/what-of-seniors-vaxxed-for-flu-c19-rsv-dec-28-mar-29/) and I got an "invalid forecast values" error. Opening the question in a different showed that none of my predictions had been saved. I played around with the sliders and finally one of my predictions went through, but the other had simply vanished and I was seeing the default distribution.

**Comment by nangchrys** [comment]
It happened again in the RSV: March 29, 2024 subquestion:
![image](https://github.com/user-attachments/assets/92d63e5d-4f39-4532-86de-78b6da6b45d5)

**Comment by lsabor** [comment]
This has been addressed by another ticket.
Shouldn't be possible to make invalid forecasts with the sliders now.
