### ISSUE TITLE
Make "resolving soon" filter out resolved questions

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1156]
## Current behavior
Ordering by "[Resolving soon](https://www.metaculus.com/questions/?order_by=scheduled_resolve_time)" includes questions that have already resolved:
![image](https://github.com/user-attachments/assets/911151eb-a00a-47c6-b541-7c411d2d41e9)

## Expected/desired behavior
"Resolving soon" should sort by *scheduled resolve time* AND filter to non-resolved questions. 

Reported by [Jgalt](https://www.metaculus.com/notebooks/28734/#comment-208900)

**Comment by ncarazon** [comment]
Looks like @lsabor fixed it here: https://github.com/Metaculus/metaculus/commit/c0171027a08b0ffcf28f5155d88b83a7e4acbf99

The fix should be ready to test on prod

**Comment by SylvainChevalier** [comment]
I'm getting a bunch of deleted questions. It should only have approved questions.
