### ISSUE TITLE
Fetch error in date range groups

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1167]
I tried to create a date range group of questions.

When I entered the closing or resolution year in question for each questions, if I enter a fifth number by mistake, there is an error that cancels everything done for the question.

**Comment by hickman-santini** [comment]
Ope, my mistake, that wasn't a GROUP date range question that I tried it on. Now I tried to create a group date range question like ten minutes ago with a five-digit year and it's just loading interminably for me. Thanks for reporting.

@ncarazon when you get to this, just add the same input validation as we have on non-group date range questions.

**Comment by ncarazon** [comment]
TODO: add Awaiting QA label once dev deploys are enabled again

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm

**Comment by exmateriae** [comment]
Thanks! There are still some bugs related to the behaviour of the dates but I've been unable to reproduce them easily (they did not give the same error) so I'll make a new issue later.
