### ISSUE TITLE
mention notifications separately from other notifications

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1170]
Currently, if a user tags you in a comment, you are notified in the same way as if a new comment was posted on a question you're following. This means that such notifications might get lost and also makes conversations slower as the new comment notifications are sent every hour.

I'm proposing to bring the old system of notifications back, where you got separate emails for them that weren't bundled with the new comment emails and they were instant.

**Comment by SylvainChevalier** [comment]
Will be done in #1006.
