### ISSUE TITLE
In Admin, the 'Prize pool' field should default to blank instead of 0.00

### ISSUE THREAD

**Issue by christianMet** [Metaculus/metaculus#1186]
## Current behavior
Pages like this one (question series and tournaments): https://www.metaculus.com/admin/projects/project/3682/change/?_changelist_filters=q%3Dpensacola

on creation have prize pool fields that default to 0.00. When pages are created, the header says prize pool $0. Most series will have $0. So, rather than displaying the $0, we delete the default value there, and it disappears from the header. 

## Expected/desired behavior
The default value should be blank instead of 0.00 so the header will not by default feature Prize Pool $0.

**Comment by lsabor** [comment]
You should be good to go with new tournaments not having populated prize pools.
I also very quickly removed 0$ prize pools in general. I think that the rewrite migration defaulted to adding 0$ there.
New tournaments should be default-populated with nothing.

**Comment by christianMet** [comment]
Thanks Luke

Christian Williams
Director of Communications and Data | Metaculus
<https://www.metaculus.com/about/>
