### ISSUE TITLE
Change fan graph card details (in the feed)

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1214]
One thing I just realized, this stuff on the left is pretty meaningless in the feed for grouped questions, would probably be better to just show the fan graph full width or something.

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1730409650520119?thread_ts=1730409572.191489&cid=C01Q9AQBVHB)

![image](https://github.com/user-attachments/assets/674edabe-808a-482d-8369-39ea616e7725)

TBD what we want to do instead; I'd like to get @SylvainChevalier thoughts

**Comment by SylvainChevalier** [comment]
We can do whatever non-fan-graph groups do:
![image](https://github.com/user-attachments/assets/07c6aa08-9723-43ab-aa53-95e91aeca5a6)

**Comment by hickman-santini** [comment]
Excellent! @SylvainChevalier something like this? I know not high priority but I was inspired...

![image](https://github.com/user-attachments/assets/be924026-a7ef-4f1f-b8e3-4a7f2ca731b7)
_(Not real data, just sort of based on flu hospitalizations graph)_

Pretend I put diamonds in front of the resolutions that weren't annulled. For fan graphs, the groups should always be ordered in reverse chronological order -- the most recent three, then "X more..." like we do with non-fan-graph groups:

![image](https://github.com/user-attachments/assets/c8408c63-d1e4-40a6-a565-110b2c82977d)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
Looks great!
