### ISSUE TITLE
Clicking question on Leaderboard leads to different question

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1222]
## Current behavior
When I click on the second question on the AI Benchmarking Leaderboard (about the Yankees), I'm sent to a different question in a different tournament. 
<img width="1117" alt="Screenshot 2024-11-01 at 2 43 08 PM" src="https://github.com/user-attachments/assets/6bd7b320-e128-4c66-b2a2-6fde9cb55f20">
<img width="1240" alt="Screenshot 2024-11-01 at 2 43 21 PM" src="https://github.com/user-attachments/assets/19dbe3d4-7f4a-47e3-8d14-7b5c7e3f7b78">
Yankee question on this page: https://www.metaculus.com/tournament/aibq4/
Clicking sends me here: https://www.metaculus.com/questions/29028/

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by draaglom** [comment]
I'm not _positive_ but I think it's linking based on `question_id` when it should be linking based on `post_id`

**Comment by draaglom** [comment]
I've pushed a hotfix for based on that educated guess! #1223

**Comment by lsabor** [comment]
I think this was addressed by #1225
@Tommetaculus please QA this and close if complete.

**Comment by lsabor** [comment]
Fixed the problem where unscored contributions weren't linked before. Scored ones still aren't linked. Fixing

**Comment by lsabor** [comment]
Fixed all. I'll close if Tom approves here or in slack.

**Comment by Tommetaculus** [comment]
Works! Thank you Luke!
