### ISSUE TITLE
Cannot forecast on question

### ISSUE THREAD

**Issue by draaglom** [Metaculus/metaculus#1230]
## Current behavior

https://www.metaculus.com/questions/29242/

<img width="764" alt="image" src="https://github.com/user-attachments/assets/88012e1f-9c32-4f67-b71a-27560b4742d3">

1. Visit this question
2. submit a forecast
3. In the UI: observe
      - an apparently successful forecast
      - in the top nav, 'closes in 2 days'
4. In the network inspector: observe
      - `{"error":"Question 29145 is already closed to forecasting !","message":"$undefined"}`
5. Reload the page and observe the forecast was not successful

## Expected/desired behavior

- If a forecast is not successful, the UI should give some feedback to reflect that
- If this question is in fact closed, the forecasting controls should be disabled and the timer should say "resolves in X days" instead (or something like that)
- If the question is supposed to be open, a forecast should be allowed :-)

**Comment by lsabor** [comment]
"Closes in 2 days" is likely reading from the Post object rather than the Question object.
I think we should eliminate all timing fields from the Post object and just infer these things from the question / questions at serialization time. it won't be that much to check.
