### ISSUE TITLE
Continuous question not remembering scale settings when editing

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1239]
I'm trying to edit this pending group question: https://www.metaculus.com/questions/29507/us-weekly-influenza-hospitalizations-24-25/

Each subquestion had both bounds set to open. However, when I edit it the bounds are both unchecked. Additionally, when I edit the scale of a subquestion, only the "min" and "max" get remembered on next edit. Logarithmic scaling does not get remembered.

The edits implement properly, it's only in the edit interface where it "forgets" the settings.

For example, on the subquestion below previously the bounds were both checked and logarithmic scaling was checked with a zero point of 0. But after clicking edit they're now not remembered.

![image](https://github.com/user-attachments/assets/c116dbf8-0183-46cc-9205-22fcf5f171d5)

**Comment by ryooan** [comment]
Marking as high priority because it's a pain and I'm concerned something is going to get screwed up due to this.

**Comment by lsabor** [comment]
Reproduced locally.
Seems to only effect continuous group questions, which is good. But upon saving it does in fact forget those settings. Working on the fix.

**Comment by lsabor** [comment]
Fix was reasonably straightforward. Closing as complete. Will be on production at next deployment.
