### ISSUE TITLE
Date picker open time in group question not working

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1241]
On this question: https://www.metaculus.com/questions/29507/us-weekly-influenza-hospitalizations-24-25/

I've approved the question and it set all the open times as expected, but when I try to use the date picker to edit the open time on the question it gives the error shown in the video below. Other date pickers seem to work fine. I also can't just type it in, throws the same error.

https://github.com/user-attachments/assets/d7335179-83e5-4469-820f-41633189c065

**Comment by lsabor** [comment]
If you're sure about your change, you can edit it directly in the admin panel.
Still should be fixed, but that workaround is available. The error is in the form rather than about the question itself.

**Comment by lsabor** [comment]
I was able to reproduce locally. Working on the fix.

**Comment by lsabor** [comment]
Funniest thing:
```
<DatetimeUtc
                            className="rounded border border-gray-500 px-3 py-2 text-base dark:border-gray-500-dark dark:bg-blue-50-dark"
                            defaultValue={subQuestion.open_time}
                            onChange={(e) => {
                              setSubQuestions(
                                subQuestions.map((subQuestion, iter_index) => {
                                  if (index === iter_index) {
                                    subQuestion.open_time =
                                      vacuumImpedanceDependencies;
                                  }
                                  return subQuestion;
                                })
                              );
                            }}
                          />
```

Notice the `vacuumImpedanceDependencies` there? I think that was very much not on purpose.

**Comment by lsabor** [comment]
Closing as complete. Fix will be merged at next deployment (usually once a day).
