### ISSUE TITLE
Deleted questions still appear

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1255]
## Current behavior
Deleted questions in AIB still appear on the leaderboard. The posts were set to deleted in admin.
https://www.metaculus.com/tournament/aibq4/
![Screenshot 2024-11-04 at 1 39 18 PM](https://github.com/user-attachments/assets/83caee43-6bda-4001-8608-f5926f9813f2)

![Screenshot 2024-11-04 at 1 40 08 PM](https://github.com/user-attachments/assets/feb17d1d-2e35-4080-a9a0-848b4f31fc15)

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by lsabor** [comment]
Ok scores deleted. you may have to rerun the leaderboard calculation. Closing as complete

**Comment by lsabor** [comment]
Wait a second, they'll still be appearing in the contributions section, just without scores. one moment.

**Comment by lsabor** [comment]
Ok, I found a much better solution that deleting the scores. Instead, when a project is determining which questions do or do not count towards a leaderboard, it just discounts any questions with invalid statuses (draft, deleted, rejected). This way the scores can stay in memory in case a deletion act is accidental and the admin wants to reverse the choice.
Also, the code is cleaner this way.

Apologies, I have deleted the scores on the deleted [PRACTICE] questions. If you want them to re-appear you'll have to unresolve and then re-resolve them or ask me to manually repopulate the scores.

Re-closing as complete. Effect will be seen at next deployment - and again you'll still have to rerun the leaderboard update.

**Comment by Tommetaculus** [comment]
@lsabor Just to be explicit: Deleted questions should not show up anywhere on the frontend including the feed & scoreboard.

**Comment by lsabor** [comment]
I haven't touched how the feed works, but I think the answer is yes.
What I've done is just added those filters for the "contributions" section (the part that shows up when you open "my score") and the behind-the-scenes math that actually aggregates your contributions into a leaderboard position. They actually use the same generating function, so it was only a change in one place. I've verified this result locally by playing around with deleting / restoring questions in AI benchmarking.
