### ISSUE TITLE
Make bot comments hidden (not private?) by default

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1258]
Bot comments on AIB questions are all fine and good, but they are out of place on normal quesitons:
https://www.metaculus.com/questions/29028/us-state-dept-global-arms-sales-approved-q4-2024/#comment-215912

## Desired behavior
On all non-AI Benchmark questions, make it so that the bot comments are **hidden** by default but there is a "🤖 show bot comments" checkbox to make them appear in the comment feed. Leave AIB tournaments as they are. Maybe this needs to be a setting for tournaments? @SylvainChevalier can you weigh in here?

**Comment by lsabor** [comment]
Sorry if this is a duplicate

**Comment by draaglom** [comment]
strong +1: in general, the metaculus comment section is important to my usage of the site -- users have interesting information to share, and low quality comments (especially long ones) really detract from that

with that said, humans also post unhelpful comments sometimes. I quite like reddit's approach vs a blanket hide: if comments are downvoted enough (or have a high enough ratio of downvotes vs upvotes, maybe?), start the comment thread collapsed, and you can expand it if you want to.

This would solve for both bad-quality bot and human comments, and allow for good bot comments to be shown (imagine a news bot that posted relevant updates -- might be welcomed)

The challenge with it would be that it would require active community moderation -- and there's a relatively small number of actively commenting/voting users, so it might take a while for a bad comment to accumulate enough downvotes to be hidden.

**Comment by hickman-santini** [comment]
@Tommetaculus also asked for this, citing jkraybill's bot's comment [here](https://www.metaculus.com/questions/29028/us-state-dept-global-arms-sales-approved-q4-2024/#comment-215912).

We can think about doing something like reddit's approach for future (agree that bot comments may be useful sometimes). Thanks @draaglom.

**Comment by lsabor** [comment]
closing as duplicate of #753

moving the conversation over there
