### ISSUE TITLE
Forecasts occasionally don't go through.

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1262]
[Example question](https://www.metaculus.com/questions/19056/the-keys-to-the-white-house-false-keys/) but can happen in any numeric questions, maybe date ones too.

Behavior: I click on "Save Change", it becomes grayed out, 3 dots appear below as if loading something, but less than a second later everything is as if I didn't predict and indeed my prediction hasn't gone through upon reloading. No visible error message.

Inspector message:
![image](https://github.com/user-attachments/assets/1d2e15ea-f9a2-473a-81f6-7da78d88086d)

Forecast that triggers it:
![image](https://github.com/user-attachments/assets/e8150ef9-3700-4b16-9b54-ad5b78e7b251)

The error is reliable; pressing the button again does not fix it. It can be fixed by adjusting any of the weight sliders, but appears again in different places. E.g. in the above screenshot, it happens if my bottom weight slider is at 100%, it stops if it's at 98%(?) but happens again closer to 95%. It also happens at ~50% and many other values.

No slider needs to be closer to 0, this forecast doesn't work either:
![image](https://github.com/user-attachments/assets/a9ff01bf-53cb-4d3d-a4ca-1ba14b9d6a0d)

**Comment by lsabor** [comment]
#1210 is now in QA. You should have fewer bugs and better console log statements
I created a separate ticket for displaying the debug statements in the UI for users #1296 

Minor change to cdf calculation that rounds to 10 digits might have solved the seemingly random validation values you've documented.

I'm moving this to QA accordingly.

**Comment by SylvainChevalier** [comment]
@nangchrys do you still encounter the issue?

**Comment by nangchrys** [comment]
@SylvainChevalier  Not so far.

**Comment by lsabor** [comment]
Excellent. I'm going to close this issue.
