### ISSUE TITLE
MC in feed only displaying 2 options on graph

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1293]
It should show 3. I think this was a recent change, but I could be wrong.

![383604876-e57362de-fad6-42df-9c36-b69802b85574](https://github.com/user-attachments/assets/1c9b87af-2588-4309-9719-97a35e367cdf)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
