### ISSUE TITLE
Display errors in forecast values if any

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1296]
## Current behavior
A failure to submit valid forecast values when using the sliders (yes it is possible) results in no text appearing and instead an uncaught error shows up in the Console.

## Expected/desired behavior
Display the error text below the prediction submit button.
We don't really want users to be able to use the sliders to produce invalid forecasts, but giving good debug statements will improve the feedback we get.

**Comment by lsabor** [comment]
If you want to test this locally, add
`request.data[0]["continuous_cdf"][-1] = 1.0`
to line 87 or 88 in questions/views.py, and then forecast on /questions/28423/ or any continuous question that has an open upper bound.
You'll be able to see the Uncaught error in the terminal:
```
[{
    "non_field_errors": [
      "CDF Invalid:\ncontinuous_cdf at upper bound must be at most 0.999 due to upper bound being open.\n"
    ]
}]
```

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
@lsabor happy to QA, but not sure how to reproduce. What are slider positions that trigger the error?

**Comment by lsabor** [comment]
I think I solved all the invalid slider positions, so this whole thing might be moot. But I'll QA this by overriding the forecast to be invalid and making sure the errors display.
Thanks @ncarazon

**Comment by lsabor** [comment]
This works. Closing as compelte
