### ISSUE TITLE
Remove tutorial popup on subdomains

### ISSUE THREAD

**Issue by leonardthethird** [Metaculus/metaculus#1302]
## Current behavior
Newly registered users on subdomains get a popup for a tutorials flow that doesn't work.

## Expected/desired behavior
Remove popup

**Comment by leonardthethird** [comment]
@hickman-santini Do you mind setting to High Priority?

**Comment by lsabor** [comment]
I've just realized that this isn't the right location for this issue. That is associated with the old site. Closing as not planned.
I'll carry out the work on the old site though.
