### ISSUE TITLE
Display Question Weight and Bot Inclusion status in question pages

### ISSUE THREAD

**Issue by aseckin** [Metaculus/metaculus#1313]
We're adding two rows to the question sidebar, for 'Question Weight' and 'Includes Bots'.

Each of these should have a question mark that displays a tooltip on hover.

For subquestions in a group, we use the '...' dropdown to display this information which now has a redesigned UI separating action items from subquestion details.

[Implementation Details are on Figma](https://www.figma.com/design/mjkPXmoVC1s7163RXHRoMY/Question-Weights-%26-Bots?node-id=7-10100&t=Er9MCN8u24aGDPPY-1)

![image](https://github.com/user-attachments/assets/ae27158b-b63b-440b-bc9d-3f428e516fec)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
