### ISSUE TITLE
Show number of forecasters in the feed

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1335]
I think the feed should show number of forecasters. This is very useful when interpreting a forecast you see in the feed without having to click into it, and also useful for admins to assess which questions might need more attention and therefore boosted. This was the case on old Metaculus.

Also, it would be ideal if questions where the CP is hidden still show the number of forecasters in the feed (and on the page itself somewhere too ideally). This was not the case on old Metaculus, but had been desired (at least by me).

How this looked on the old Metaculus:

![image](https://github.com/user-attachments/assets/d702e0b7-7384-45d8-bcc0-7549b6b1fdcb)

**Comment by ncarazon** [comment]
Ready for testing on prod.

Note, that I skipped this status for MC and group questions as I'm not sure where to put those on both the feed card and the individual question page. @aseckin, maybe you could provide some designs for this part?

**Comment by SylvainChevalier** [comment]
Looks great on single questions. Agree we need designs @aseckin. I personally can't think of a good place to put it, except making the tile taller.
![image](https://github.com/user-attachments/assets/5a600da1-7459-49a1-b127-bce6b667f45c)

**Comment by aseckin** [comment]
I don't think we have room for this in group tiles, we'd need to do a redesign to make space for it without making things too cluttered.

**Comment by SylvainChevalier** [comment]
ok, closing this then.
