### ISSUE TITLE
Allow date range filtering of calibration view

### ISSUE THREAD

**Issue by pgodzin** [Metaculus/metaculus#1336]
## Current behavior
The current calibration view is for all-time

## Expected/desired behavior
Would like to be able to view the calibration for a specific time interval (q3 vs q4 for example). 

It may not be as useful for a human forecaster whose predictions may not change much over time, but for a bot whose underlying models and prompts change, it'd be nice to visualize if my attempts to improve calibration have worked from quarter to quarter.

**Comment by draaglom** [comment]
as a human forecaster it would be useful too! I update my """underlying models and prompts""" too (e.g. deliberately trying to be less agreeable, or devoting more or less time to forecasting, or learning more stats)

**Comment by SylvainChevalier** [comment]
I agree this would be good! This and other improvements to the track record are planned, but not at the top of the priority queue right now.
