### ISSUE TITLE
close time validation

### ISSUE THREAD

**Issue by EloiseRosen** [Metaculus/metaculus#1346]
![image](https://github.com/user-attachments/assets/689202a3-f9ac-407e-a623-f26c5b1ce733)
(from https://www.metaculus.com/question-writing/)
The stated requirement for the close time to be at least 1 hour before resolution time seems to not be enforced. I am able to create and approve a question with identical closing date and resolving date:
![image](https://github.com/user-attachments/assets/4cb0cd52-4bb5-470d-a29a-ed29954849d2)
![image](https://github.com/user-attachments/assets/9049a765-7b1c-43a6-b0f0-980dc5a119f6)

In fact, I'm able to create and approve a question where the closing time is _after_ the resolution time.
![image](https://github.com/user-attachments/assets/2324d798-0e25-4288-bd63-4271f517c76a)

**Comment by SylvainChevalier** [comment]
> I am able to create and approve a question with identical closing date and resolving date:

That's fine, we should updated the FAQ.

> I'm able to create and approve a question where the closing time is after the resolution time.

That's not fine.
