### ISSUE TITLE
"Scoring Terminology" section of AIB says Relative instead of Peer

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1370]
## Current behavior
The "Scoring Terminology" section of AIB uses relative score. It should use the Peer scoring language, similar to the Quarterly Cup.
https://www.metaculus.com/tournament/aibq4/
![Screenshot 2024-11-12 at 8 47 52 AM](https://github.com/user-attachments/assets/24ba8c47-90b7-482b-9775-835a7cd51e8a)

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by SylvainChevalier** [comment]
@lsabor probably the spot peer score leaderboard type not being recognised?

**Comment by lsabor** [comment]
fixed. closing as complete. Will be evident in next deployment
