### ISSUE TITLE
Question creation pdf graph crashes on invalid date

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1371]
If I press 0 here
![image](https://github.com/user-attachments/assets/0e72ed50-bed0-4402-bb6a-5e7ba9f8a1c2)
I get this
![image](https://github.com/user-attachments/assets/d6e2a9ea-fe74-414b-8b70-9101c291d46b)

I assume because the creator is trying to make a graph with an invalid date. I know I don't need to press 0 for anything (I can just do 1 for 01), but if I forget and press it I lose all of my progress on the question.

**Comment by SylvainChevalier** [comment]
tbc, to reproduce:

- create date qestion
- enter valid min and max dates
- the pdf graph appears
- enter 0 in either min or max date
- error
