### ISSUE TITLE
Jgalt reports not being able to update prediction on group question

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1372]
>[@admins](https://www.metaculus.com/faq/#admins-tag) I seem to be unable to update my prediction on question groups; I tried updating my 2025 prediction on [this question](https://www.metaculus.com/questions/11600/next-us-economic-recession/) but my changes aren't being saved. There's no error message after attempting to update; everything looks normal, but when you refresh the page, you can see the change has not been saved.

**Comment by lsabor** [comment]
from this comment: https://www.metaculus.com/notebooks/28734/a-massive-rewrite-a-slate-of-improvements-and-going-open-source/#comment-221459

**Comment by lsabor** [comment]
I was unable to recreate any issue locally.

**Comment by SylvainChevalier** [comment]
Duplicate of #1362
