### ISSUE TITLE
Question weight in API is wrong for AIBQ4

### ISSUE THREAD

**Issue by TeunvdWeij** [Metaculus/metaculus#1385]
## Current behavior
If I get the content of questions through the API, the weights for the prime minister of Iceland and UD active oil drilling rigs are 1, while on the website they are 0.5. 

Question ids are 29876-29879, and 29872-29875.

## Expected/desired behavior
The website and api leading to the same question weight. Although AFAICT, other question weights seem correct.

**Comment by SylvainChevalier** [comment]
I just checked the Iceland question, and it has a weight of 0.4644, which is consistent with what I see on the site.
![image](https://github.com/user-attachments/assets/c30c3306-4768-4855-b7e1-8cb0eaf0d007)
I spot checked a few others and didn't see a problem. Do you still see the issue?

**Comment by TeunvdWeij** [comment]
Thanks for the quick response! 

I also do not see it any more now that I have refreshed. It could be a bug which updates the question weight later?

**Comment by TeunvdWeij** [comment]
Feel free to close btw because this is not a high priority any more I think, but it might be worth monitoring the next batch of questions as they come out on the question weight.
