### ISSUE TITLE
Add 'ugc' attribute to links in user generated content

### ISSUE THREAD

**Issue by aseckin** [Metaculus/metaculus#1421]
We should add the rel='ugc' attribute to the links submitted as part of user comments and profile bios, to not reward the spam accounts that post ads. We moderate the comments more strictly so that's not a big issue, but for spam profiles we don't yet have a solution. [(being discussed here)](https://github.com/Metaculus/metaculus/issues/1386)

More info on the attribute: https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links

**Comment by SylvainChevalier** [comment]
Can't see it, either on [my bio](https://dev.metaculus.com/accounts/profile/105951/) or [this comment](https://dev.metaculus.com/notebooks/28734/#comment-224152).

**Comment by ncarazon** [comment]
@SylvainChevalier 

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/86fcf3b3-e194-4787-9ec1-40ec76390c7e">

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/c1f413ef-e8b8-4060-999b-0ac143c360bf">
