### ISSUE TITLE
Show empty graph, forecaster count, and disclaimer before CP is revealed

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1428]
When the CP is hidden because the CP reveal date hasn't been reached before, we should show:

- In the feed, an empty graph with the forecaster count
![image](https://github.com/user-attachments/assets/84442030-2e7e-48d8-a209-95b66ba4b0e8)
- On the question page, an empty graph with the forecaster count
![image](https://github.com/user-attachments/assets/c4e24ed7-9cfc-4c54-b5c5-52ec2f69405d)

Note: this is already done for users who hide the CP in their settings, see #937.

Nice to have: include a disclaimer on the graph.
![image](https://github.com/user-attachments/assets/1fa990aa-369a-451a-844f-28fa62cb7455)

**Comment by ncarazon** [comment]
@SylvainChevalier I'm not sure how we should adjust the rendering for group and conditional questions. What design should we implement for conditional types, and how should we determine whether or not to render an empty chart with a message (in edit form the user is able to set different timestamps for CP reveal time on group questions)?
One option could be to check the reveal time for each subquestion. If all of them have not been revealed yet, we can render an empty chart with the earliest `cp_reveal_time`.

**Comment by SylvainChevalier** [comment]
Yes, for group let's show the empty graph + message only if all subquestions are before their reveal date.

For conditionals we can have the same copy, where the predictions should be:
![image](https://github.com/user-attachments/assets/14864ccc-4e01-425c-a7db-976311cb5bdf)

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
Perfect and on prod :+1:
