### ISSUE TITLE
Don't truncate question text in embeds

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1442]
I think this may have been fixed in the feed, but it's still the case that embeds truncate so you can't see what the question is fully asking.

![image](https://github.com/user-attachments/assets/499b1da6-c743-4f84-8002-164a2d3ecc58)

![image](https://github.com/user-attachments/assets/f93f7cdf-ea52-4a9e-b048-5a0f69c431f1)

**Comment by ncarazon** [comment]
Ready for testing on prod
