### ISSUE TITLE
Group label is broken on group questions

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1443]
I believe this says "TBD group label" as a placeholder and should be fixed to show what the actual label has been set to. For example the one below should say "week ending". Link to question: https://www.metaculus.com/questions/30049/us-covid-hospitalization-forecasts-2024-25/

![image](https://github.com/user-attachments/assets/d4963862-6bff-45d9-a6bb-82471e2fe5ce)

![image](https://github.com/user-attachments/assets/3d809e8a-c728-4ec3-8b60-dd2de1eae14a)

**Comment by nangchrys** [comment]
It says TBD group label when they have resolved and nothing when they haven't, [e.g.](https://www.metaculus.com/questions/27811/total-points-in-24-25-premier-league/):
![image](https://github.com/user-attachments/assets/5c9c80c0-2068-4f91-973a-db8cdb8e686f)

This is only for continuous group questions. For binary group questions and MC questions it always says "Candidates", [e.g.](https://www.metaculus.com/questions/17299/civil-war-before-2036/):
![image](https://github.com/user-attachments/assets/d326d6a1-566a-444c-b5c0-f9897a2654c2)

**Comment by hlbmtc** [comment]
I see we don’t have `group_variable` for multiple choice questions anymore, just for group. Is this okay or we should bring it back?

**Comment by hlbmtc** [comment]
Fixed group of question labels, added group variable to multiple choice questions and migrated labels from old db to the new one
