### ISSUE TITLE
Bot forecast in question feed does not match distribution

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1452]
## Current behavior
When submitting a numeric forecast via API, the median forecast shown in the feed does not match the PDF.
![Screenshot 2024-11-19 at 11 45 54 AM](https://github.com/user-attachments/assets/e9cbf84b-7fda-4a42-8315-732a0f24d3ae)
The Elon Musk question says 79.9, but the actual median is below 50.
The Brazil question median is 240, but the feed says 250.

This is blocking for AI Benchmarking doing numeric questions, since it is the only way for users to see their bot's forecast - which is not implemented on the question detail page.

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by Tommetaculus** [comment]
Notably, the reported forecast says the correct median on the question detail page. In this case it says 50 on QDP, but 79.9 in the feed.

![Screenshot 2024-11-19 at 11 53 02 AM](https://github.com/user-attachments/assets/840fa434-3210-45ff-8857-b3f76258b8bc)

**Comment by SylvainChevalier** [comment]
ok, closing.
