### ISSUE TITLE
Make onboarding trigger when first visiting feed or homepage

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1454]
# Current

You get the onboarding flow when following the email confirmation link.

# Desired

You get the onboarding flow when visiting /home/ or /questions/. If you complete it or skip it you don't get it anymore.

**Comment by hlbmtc** [comment]
@SylvainChevalier Currently, you're always redirected to homepage when following activation link

**Comment by hlbmtc** [comment]
@SylvainChevalier Currently, following the activation link always redirects you to the homepage. This should probably be implemented after we update the activation logic to remember the page you signed up from

**Comment by SylvainChevalier** [comment]
> implemented after we update the activation logic to remember the page you signed up from

No need, it's fine if you get the onboarding flow when you follow the confirmation link. That's the current behaviour, so no loss.

This will be very useful for a coming Program, do you think you can get to this by end of next week?

**Comment by hlbmtc** [comment]
@SylvainChevalier Sure, I've just opened a pull request -- https://github.com/Metaculus/metaculus/pull/1486
