### ISSUE TITLE
Axis labels repeat themselves when question open for < 1 month

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1459]
## Current behavior
This question had its first forecast on Sep 18, 2024 and closed Sep 30.
![image](https://github.com/user-attachments/assets/e5c0bd42-1b31-43cf-bece-6e993db99056)

## Expected/desired behavior
Axis labels should be day-level.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
@hickman-santini reminder to put links in issues for easier testing.

looks like this is on prod, closing.
