### ISSUE TITLE
User Predictions are missing for some questions in feed cards

### ISSUE THREAD

**Issue by ncarazon** [Metaculus/metaculus#1477]
## Current behavior
Reproduced for binary questions:

![image](https://github.com/user-attachments/assets/b39969ed-9765-4664-973c-b86ee15371cb)

## Expected/desired behavior
User predictions are correctly displayed on the feed tile.

**Comment by SylvainChevalier** [comment]
@ncarazon I don't know how to reproduce.

**Comment by ncarazon** [comment]
@SylvainChevalier user CP score was missing on post cards for open questions 

<img width="767" alt="image" src="https://github.com/user-attachments/assets/788fc9c6-f93b-43cb-88c1-f244dbadb007">

**Comment by SylvainChevalier** [comment]
Looks fixed to me, closing.
