### ISSUE TITLE
Make rationales collapsible to fit more on page

### ISSUE THREAD

**Issue by catskillsresearch** [Metaculus/metaculus#1487]
## Current behavior
It currently requires 5 presses of "More" to see 1 day's worth of bot comments on the Q4AI competition, because the comments are so verbose.

## Expected/desired behavior
Make the comment text be a collapsed expandable div where you see only the first line to start with and can press on it to see the rest.  Add an option at the top of the page to show all comments on one page.

**Comment by SylvainChevalier** [comment]
We always load the 10 latest comments when loading a question page, regardless of their length. We have plans to make bot comments collapsed by default (see #1523), which I believe would solve this issue.

**Comment by catskillsresearch** [comment]
It would be nice to be able to set a preference to load all comments assuming they are collapsed.  For Q4AI tournament I typically need to load all to get down to my own comment or those of some other bot I want to check.
