### ISSUE TITLE
Add message about timezone to resolution modal

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1492]
Somewhere in this modal it should say whether the dates and times shown are in local time or UTC.

![image](https://github.com/user-attachments/assets/108e615c-0a76-4887-8ce1-c74aea9e0fc2)

**Comment by ncarazon** [comment]
@ryooan could you provide a text copy for the message we should show?

**Comment by ryooan** [comment]
@ncarazon below each date / time field in small italics: "Date and time is in your local timezone [UTC+X]"

Assuming it is local. Also the UTC part is just an idea, more of a nice to have, so if not easy to do I'd skip it.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm.
