### ISSUE TITLE
Don't plot fan graph points where there's no forecast

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1494]
I just opened some new subquestions in an existing question, and where there's no forecast yet the fan graph is plotting as shown. It should instead not plot points where there's no CP. https://www.metaculus.com/questions/22134/unemployment-in-australia/

![image](https://github.com/user-attachments/assets/b26a5a7f-b4cb-4a92-b56f-49408e0a6e20)

**Comment by SylvainChevalier** [comment]
lgtm
