### ISSUE TITLE
Formatting long quotes is janky

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1496]
## Current behavior
@leonardthethird had to use empty space characters to get the quote with paragraphs here to show up nicely (background info): https://www.metaculus.com/questions/30258/low-level-of-universal-basic-income-by-2030/

## Expected/desired behavior
Can we make it so that you can use normal space characters?

`> this is the first thing`
`> `
`> this is the second thing`

**Comment by SylvainChevalier** [comment]
Both comments and question texts strip empty quote lines.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
