### ISSUE TITLE
Combine "unlisted" and "in main feed"

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1508]
Tournaments have a field "visibility", that can be either "normal", "not in main feed", "unlisted".

Only has effect on tournaments, question series, and communities.

|                                        | normal                      | not in main feed | unlisted | (private) |
|----------------------------------------|-----------------------------|------------------|----------|-----------|
| gives medals                           | tournaments                 | none             | none     | (none)  |
| questions count in yearly leaderboards | tournament, question series | none             | none     | (none)  |
| questions show in main feed            | tournament, question series | none             | none     | (none)  |
| content findable in search engines     | all                         | all              | none     | (none)  |
| show in tournaments/communities pages  | all                         | all              | none     | (none)  |

@ryooan adds: Ideally if there's some explanation in admin in the project page or somewhere handy of what all the settings do (like Sylvain's table there), that would be beneficial. I'd like to avoid uncertainty in what toggles should / should not be selected.

[Edit:] added the (private) column as a reminder, but tbc "private" is _not_ one of the options in the "visibility" field.

**Comment by hickman-santini** [comment]
Yes!!! This is exactly what would have been useful for the curve, I think for a lot of workshop/conference type settings.

**Comment by hlbmtc** [comment]
related #1621
