### ISSUE TITLE
Filter the feed by followed status

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1536]
Copying from [spec](https://www.notion.so/metaculus/Followed-feed-13c6aaf4f101803498cdf37f8a3994c0):

There is a new feed filter: My Participation → Following

It returns posts the user follows, even if they set no reminders.

![image](https://github.com/user-attachments/assets/0b200316-75c3-453f-950c-0a89fa0457a6)

The filter is available on all feeds: Feed Home, My Predictions, …, Tournament feeds, Community feeds, …

A shortcut is available in the Feed Home only:

![image](https://github.com/user-attachments/assets/9c4ff9f2-f592-445f-9ae1-f26dae680a94)

**Comment by ncarazon** [comment]
Ready for QA on dev

**Comment by SylvainChevalier** [comment]
lgtm as speced.

amendments in #1581.
