### ISSUE TITLE
Change contributions page URL schema

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#1546]
## Current behavior
I suspect our CDN bans might be related to how we structure contribution links for individual users. Currently, all categories and users are handled by a single page with query parameters like /contributions/?user=1&category=category&....

This pattern is unideal because CDNs typically do not differentiate query parameters. As a result, pages like /contributions/?category=peer&user=156511 and /contributions/?category=peer&user=148850 are likely treated as a single page, which might lead to throttling limits being applied as if they were the same resource..

## Expected/desired behavior

- [x] Change contributions page pattern to contributions/<category>/<userID> 
- [x] Create a backward compatibility redirect page from ` /contributions/?user=1&category=category&...` to `contributions/<category>/<userID>?other_query_params`

**Comment by ncarazon** [comment]
Ready for QA on dev
