### ISSUE TITLE
Tournament search bar is broken

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1564]
The tournament search bar doesn't appear to work.

![image](https://github.com/user-attachments/assets/d7040472-c0f7-4bb2-b157-e4a72ab88847)

**Comment by ryooan** [comment]
Went ahead and marked this high priority.

**Comment by SylvainChevalier** [comment]
@elisescu caused by new search bar?

**Comment by ncarazon** [comment]
@SylvainChevalier I actually have a fix already, will push a fix soon

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
