### ISSUE TITLE
Display both my and community prediction in the feed (as text)

### ISSUE THREAD

**Issue by jkraybill** [Metaculus/metaculus#1571]
## Current behavior
Currently if I predict a question that is open, I see this:

<img width="573" alt="image" src="https://github.com/user-attachments/assets/936f387b-f3e1-4078-ba5c-dd08550a68c0">

But once that question is closed, I see this:

<img width="575" alt="image" src="https://github.com/user-attachments/assets/5d260c51-83bf-468d-a163-edb7a55cbd25">

## Expected/desired behavior

I'd like to see:

1. my own personal prediction (the "89.5%" in the first image) remain there after community predictions are visible; and
2. the community prediction to be rendered, in text, somewhere around the left of the chart.

Mockup of what I'd love to see below:

<img width="575" alt="sc-000040b" src="https://github.com/user-attachments/assets/de6f291a-1f98-44f6-be6e-998868fb25d2">

**Comment by SylvainChevalier** [comment]
Thanks @jkraybill. We are in the process of refactoring the feed tiles, so will keep that in mind. cc. @aseckin
