### ISSUE TITLE
Put Followed filter in sidebar

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1581]
From [Slack](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1733355064210249?thread_ts=1733351907.574489&cid=C01Q9AQBVHB).

We should make 'Followed' a sidebar item, it pairs well with My Predictions and My Questions. Hot-Movers-New are a set of user-agnostic shortcuts and Followed doesn't belong there.

Also when Followed is active and I click through different topics, the filter persists and I get no results most of the time. It should behave like how My Predictions behaves, where the filter resets when I switch to different topics.

We can use the :mag_right: emoji and call it "Following" in the sidebar.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
