### ISSUE TITLE
Group question chart is showing the wrong forecast

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1598]
Sharing for awareness and adding this as github as a high priority issue, seems like group question charts are showing the wrong information. <https://www.metaculus.com/questions/26256/peak-respiratory-magnitudes-2024-2025/#comments>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1733414350479699)

![image](https://github.com/user-attachments/assets/62b3847b-3c7f-450c-9d0d-d4f102d4ba1b)

**Comment by ryooan** [comment]
Looks like it's only when you untick one or more options under the chart that it begins showing wrong numbers.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
LGTM
