### ISSUE TITLE
Include public projects in global leaderboards unless otherwise specified

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1621]
Previously on old Metaculus a question was included in the public leaderboard if it was a public question, by default.

I hadn't realized this had changed for the rewrite, so there are now a bunch of questions which were submitted directly to certain projects which should appear in global leaderboards, but no longer do.

For example, this question: https://www.metaculus.com/questions/28834/2024-world-chess-champion-in-the-first-10-games/

After talking to @lsabor, the issue seems to be that now only projects in the Metaculus Community project count towards global leaderboards. Mods and admins don't add every question to Metaculus Community, and this would be kind of a pain to remember, so we should have some clear system at the project level for ensuring everything that should count toward global leaderboards does.

This could be a checkbox on a project page that says "counts toward global leaderboards" or something like that. Not sure what the solution is, just that we need to do something differently because we're likely currently missing a bunch of questions from global leaderboards that should be counted there. Any question submitted directly to a tournament/project currently is at risk of not counting for the global leaderboard when it should count.

**Comment by SylvainChevalier** [comment]
@hlbmtc I once again advocate for stopping using the `site_main` project for this.

**Comment by hlbmtc** [comment]
Will be on dev during the next deploy
