### ISSUE TITLE
Pro Forecasters page

### ISSUE THREAD

**Issue by ncarazon** [Metaculus/metaculus#1647]
Tasks:

- Implement the About Metaculus Pro Forecasters flat page
- Link to it from the top of the Leaderboards page
- Link to it from the Engage With Metaculus section on Homepage
- Link to it from the FAQ Pro section

Spec: https://www.notion.so/metaculus/Info-Pages-1446aaf4f10180aea0afcb95ebaf04df?pvs=4
Design: https://www.figma.com/design/K8kO3m5QUh8dtfMtGcS7Yu/Pro-Forecasters?node-id=4-404&node-type=section&t=kMsU4qU23t9Jbfvy-0

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by ryooan** [comment]
This looks good to me and looks like it's live on prod.
