### ISSUE TITLE
User tags are working unreliabily

### ISSUE THREAD

**Issue by CodexVeritas** [Metaculus/metaculus#1658]
Jgalt helped bring this up mentioned that user tags are not working reliably in this thread https://www.metaculus.com/notebooks/30885/follow-predict-withdraw-find-predict-again/#comment-238626

@ Admins is underlined, but other @ user mentions do not have links or highlights

**Comment by SylvainChevalier** [comment]
lgtm.

**Comment by ncarazon** [comment]
Re-opening, as there are some cases when some mentions are not parsed correctly:

> User mentions don't seem to be working all the time ([example1](https://www.metaculus.com/questions/31072/will-openai-create-agi-and-announce-it-as-agi-before-2030/#comment-241020), [example2](https://www.metaculus.com/questions/31153/will-the-myanmar-junta-collapse-in-the-next-few-months/)). Sorry for not creating an issue, I'd like to avoid having skmmcj & nangchrys publicly associated.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by hickman-santini** [comment]
Those two examples now work on prod but I'm curious why/how they were breaking? @ncarazon what was special about those tags?

**Comment by ncarazon** [comment]
Mention parsing didn't work due to punctuation characters right after the mention
