### ISSUE TITLE
Adding the "followed" filter should not bring the "Following" feed

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1686]
Steps:

- Go to "Home" or "My Predictions" feed
- Open filter menu
- Select "Followed" filter

Current behaviour: you get to the "Following" feed.
Desired behaviour: you stay on the same feed, but only see questions you're following.

Said another way: the filters in the "My Participation" section should not be mutually exclusive.

**Comment by ncarazon** [comment]
Ready for testing on prod
