### ISSUE TITLE
Show Spot Scores on question page

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1708]
## Current behavior
For AI Benchmarking, we use spot scoring. However the question detail page shows time-average scoring for bot and the CP.

## Expected/desired behavior
~Show spot scores for questions that belong to a leaderboard that uses spot scoring - both for the user and the CP.~

Show spot scores on all question pages, in the Additional Scores section. Like this:

![image](https://github.com/user-attachments/assets/64223987-3a39-4e05-8311-e6f0edf324a3)

**Comment by Tommetaculus** [comment]
This doesn't cost me a lot of time, but I'm hoping it is easy - and it would be very nice.

**Comment by SylvainChevalier** [comment]
Edited top comment to flesh out.

**Comment by lsabor** [comment]
So User Spot Peer Score is already displayed in the drop down. I assume you just want to add the Community Spot Peer Score then?

**Comment by SylvainChevalier** [comment]
I don't see the spot score on my resolved questions, I assume it's only there on questions in spot score tournaments? Instead it should be visible on all questions regardless of tournament.

**Comment by SylvainChevalier** [comment]
@lsabor I can't see my spot score on https://www.metaculus.com/questions/3820/btc-worth-over-100k-usd-by-2025/.

![image](https://github.com/user-attachments/assets/a41b923f-4682-4b85-abb9-ffb655e0619a)

Also we apparently have a "Community Beer Score" now? :beer: :smile: 

Also also could you rename "Spot Peer Score" to just "Spot Score", in both my score and the CP score?

Finally since we're here, could you add a line at the bottom of the additional scores:

> Learn more about scores [here](https://www.metaculus.com/help/scores-faq/).

**Comment by lsabor** [comment]
> I don't see the spot score on my resolved questions, I assume it's only there on questions in spot score tournaments? Instead it should be visible on all questions regardless of tournament
...
I can't see my spot score ...

So if your spot score existed, it would display there for all questions (maybe it's wonky for group questions, idk). I believe this means you didn't predict during the hidden period. If you did, then I'll have to look at the data to determine why you don't see any spot scores.

> "Community Beer Score"

Hahahah whoops!

>"Spot Peer Score" to just "Spot Score"

Sure. I'd just want to point out that we do have a "Spot Baseline Score". It doesn't actually get evaluated, but could maybe get used in the future.

>add a line at the bottom of the additional scores

ok

**Comment by lsabor** [comment]
For instance, the CP reveal time is only 2 days into [the question you linked](https://www.metaculus.com/admin/questions/question/3820/change/?_to_field=id) (March 14). [Your first prediction was on March 21](https://www.metaculus.com/admin/questions/forecast/?author_id=105951&o=3&question_id=3820). So you didn't have a live prediction at spot score evaluation time.

**Comment by SylvainChevalier** [comment]
> you didn't have a live prediction at spot score evaluation time

Ah, right. Hum... makes me think we should maybe make that clear in the ui in the future? Tbd.
