### ISSUE TITLE
Conditionals resolved appearing in stale predictions

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1716]
When using "Stale" in "My Predictions", there are always conditionals appearing first, most of them having one of the forecasts already resolved... It's useless in the scope of stale predictions and I need to load several more questions before having questions still open.

Of course I can filter and exclude conditionals but that's a weird behaviour...

**Comment by SylvainChevalier** [comment]
Probably because the prediction on the annuled conditional branch isn't ignored properly.

**Comment by hlbmtc** [comment]
Should be fixed now. @exmateriae, could you please confirm if closed/resolved conditional questions have disappeared from your feed?

**Comment by exmateriae** [comment]
I have opened three times "load more" just in case and none were appearing. Thank you!
