### ISSUE TITLE
Search filters from the same category should be disjunctive

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1717]
If I click on "Open" and "Predicted", I expect that I'll get questions that are open _and_ I have predicted on. This currently works fine.

But if I click on "Open" and "Closed", I expect that I'll get questions that are _either_ open or closed. This isn't the case currently. Instead I get the last of the two filters I selected.

**Comment by SylvainChevalier** [comment]
Added [here](https://github.com/Metaculus/metaculus/issues/893), closing this one.
