### ISSUE TITLE
Project feed: "hot" sorts by `created_at`

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1729]
Questions in feed of project pages are sorted by descending creation time when sorting by "Hot".

E.g. in the [Quarterly Cup](https://www.metaculus.com/tournament/quarterly-cup/).

**Comment by hlbmtc** [comment]
@ncarazon Could you please take a look? I assume this is FE bug only

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm!
