### ISSUE TITLE
Admin panel "primary leaderboard" tweaks

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1733]
The current system is pretty confusing. The default behavior of the "primary leaderboard" field on Projects allows admins to select from any existing leaderboard.

It would be great if it would only allow admins to select from Leaderboards which have "this project" as their project.

Also, probably add a constraint on the database level where primary leaderboards can only be selected if the Leaderboard.project is said project.

**Comment by ryooan** [comment]
Also would like to add this request from our slack thread: https://metaculus.slack.com/archives/C01Q9AQBVHB/p1733951548602969?thread_ts=1733951101.929149&cid=C01Q9AQBVHB

The request is to make it the default behavior that all question series and tournament projects have a leaderboard created by default and show that leaderboard by default.
