### ISSUE TITLE
Usernames with dashes fail in comment username mentions

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1741]
[Example](https://dev.metaculus.com/questions/27416/success-with-top-partner-before-july-2025/#comment-224193).

For reference, here are all the characters currently used in usernames: [username_characters.csv](https://github.com/user-attachments/files/18165550/username_characters.csv).

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm!
