### ISSUE TITLE
Forecast maker does not render errors happening on backend

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#1762]
## Current Behavior

Backend errors are not appearing in the frontend error container for all forecast maker components. There seem to be two main reasons:
1. The `createForecasts` action doesn’t wrap the response with `errors: error.data` like other actions do.
2. The forecast error handler doesn’t match the actual backend error response structure. Incorrect places like this:
   ```js
   if (response && "errors" in response && !!response.errors) {
     setSubmitError(response.errors[0]);
   }
    ```

You can simulate these backend error responses by sending invalid data in a local frontend build.

**Comment by lsabor** [comment]
@ncarazon I worked on this in my large "withdraw" PR. Feel free to reassign it to me if you want.
