### ISSUE TITLE
Prediction resources page missing information in table

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1798]
The table at the bottom of the prediction resources page is missing a bunch of info shown in the old table. This is also being pointed to for BW so would be nice if it could be fixed. <https://www.metaculus.com/help/prediction-resources/>

Here's what it looked like on the old site: <https://old.metaculus.com/help/prediction-resources/>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1734733264272509)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by ryooan** [comment]
Looks good, thank you!
