### ISSUE TITLE
Binary histogram charts too small in mobile

### ISSUE THREAD

**Issue by casens5** [Metaculus/metaculus#253]
## Current behavior
on binary questions, the desktop histogram looks like this:
![desktop](https://github.com/user-attachments/assets/ac4a81e6-369b-4d44-bf5c-df6486a19255)

on mobile:
![mobile](https://github.com/user-attachments/assets/2d76d3a8-a6c1-4968-bdd4-26179f813906)

## Expected/desired behavior
probably, the aspect ratio of the graph should adjust to the container's width, so that the chart stays the same height

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
Beautiful!
