### ISSUE TITLE
Fix invalid counters for number of forecasters and predictions

### ISSUE THREAD

**Issue by ncarazon** [Metaculus/metaculus#256]
## Current behavior
Right now we use `post.forecasts_count` and `post.nr.forecasters` for populating the footer section in the embed view:

![image](https://github.com/user-attachments/assets/f2c1bb9c-8f1c-42a8-9a6a-3478edcb1836)

However, BE returns invalid data compared to what we get on the question detail page.

## Expected/desired behavior

`post.forecasts_count` and `post.nr.forecasters` should represent valid counters, which properly handle different post types (e.g. groups, conditional and regular questions)

**Comment by George3d6** [comment]
Forecast count was broken because we weren't calling `update_forecasts_count` -- works otherwise

**Comment by PatMyron** [comment]
Tangential: embed previews seem to be the main UI/UX for that info for question types like conditional and group?

For conditional questions, it seems to be a regression:
https://beta.metaculus.com/questions/21475/
https://metaculus.com/questions/21475/
For group questions, it's hidden both on the main site and `beta.`:
https://beta.metaculus.com/questions/25527
https://metaculus.com/questions/25527
