### ISSUE TITLE
Markdown migration issues when images are present

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#293]
There is a problem with markdown migration. So for question 12910 there is an embedded image inside the background info which has the following structure: `<img ...atributes >` when for the markdown it should actually be `<img ...attributes />. So basically, the content is missing / at the end of an image tag.

**Comment by hlbmtc** [comment]
Same thing with https://beta.metaculus.com/notebooks/18288/alt-protein-tournament-winners/
