### ISSUE TITLE
Scoring discrepancies between beta and prod

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#297]
We should fix these. List them here and @lsabor keep us posted on your progress in resolving them.

**Comment by lsabor** [comment]
Parity has reached near completion for scoring leaderboards. The only scoring leaderboards that are out of sync are the 2024 ones.

**Comment by lsabor** [comment]
Parity reached on scoring leaderboards
parity up to participation numbers achived for non scoring leaderboards.
Nearing ticket completion

**Comment by lsabor** [comment]
The final issue for this is that moderators are included. Moving this to lower priority

**Comment by lsabor** [comment]
Moderators / non admins aren't excluded.
Also general discrepencies have been solved.
Closing as complete
