### ISSUE TITLE
Relative score, coverage and weighted coverage are missing

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#323]
@lsabor  are all of these metrics still valid ?

**Comment by lsabor** [comment]
Relative Score, Archived Relative Score, and coverage are all completed.
Weighted Coverage is imported into the Archived Relative Score, so any already resolved questions will display the weighted coverage correctly. Any future questions which resolved and have weighted coverage should be changed to no longer have weighted coverage as this will have no consequences on already known results.

I'll leave this ticket open until I've QA'd this.

**Comment by lsabor** [comment]
Weighted coverage is the only thing that needs QA still, and effects nearly nothing. Moving to lower priority.

**Comment by lsabor** [comment]
This looks correct to me. Weighted Coverage is essentially just the "Comboprediction.coverage" from the old database. It had two differences from current coverage
1. "weighted coverage" is over the "actual open period" not "scheduled open period", so a question resolving early didn't prevent users from getting 100% weighted coverage.
2. If a question has a hidden period coverage weighting, then that gets accounted for in the weighted coverage

Also worth noting that "Weighted Coverage" for any question resolving before the rewrite is actually taken directly from the old codebase and stored in the "ArchivedScore" table, which would incorporate and weighting that was going on back then. It was stored in the old "Comboprediction.coverage". Questions resolving after the rewrite no longer take hidden period coverage weighting into account, but the "weighted coverage" is still based on (1) above.

If this doesn't seem right to you, let's have a conversation about it.

**Comment by SylvainChevalier** [comment]
Sorry. Yes you are correct, we can close this.
