### ISSUE TITLE
Dates appearing as integers on date question

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#348]
## Current behavior
On continuous "when" questions, e.g. https://beta.metaculus.com/questions/21409 -- just looking at the left column here (I like the new date format on the right on beta)
![image](https://github.com/user-attachments/assets/4102a7a5-e395-4ccd-9ba6-b5b0b976fc19)

## Expected/desired behavior
![image(1)](https://github.com/user-attachments/assets/b7db7d4d-89ec-495a-b5ca-e66696a1b314)

**Comment by casens5** [comment]
possibly also the same issue on the question feed card:

![bug](https://github.com/user-attachments/assets/300833d3-63b9-4a81-832c-f768aa74698a)
