### ISSUE TITLE
Send emails to all users with tokens informing them that we're breaking the API

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#351]
1. Write/Generate the API docs
2. Find all users with an API token
3. Email them sending them the new docs

**Comment by George3d6** [comment]
@SylvainChevalier assigning this to you since you're handling / coordinating the "communications" bit around the new metaculus release.

**Comment by hickman-santini** [comment]
Note to Molly: Sync with luke or hlib about this

**Comment by SylvainChevalier** [comment]
https://metaculus.slack.com/archives/C02JGTBC7DJ/p1725373605560949

**Comment by SylvainChevalier** [comment]
@hickman-santini this is done, right?

**Comment by hickman-santini** [comment]
@SylvainChevalier yup although I need to follow up today
