### ISSUE TITLE
Missing resolve button

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#361]
Reported by @Tommetaculus 

## Current behavior
This question doesn't have a "resolve" button, even though it's closed and I'm an admin (I can see "resolve" on other questions): https://beta.metaculus.com/questions/27539 (It correctly says "pending resolution" though). Fwiw this is a FAB question.

## Expected/desired behavior
When a question is closed there should be a resolve button for admins.

**Comment by George3d6** [comment]
Has one now
