### ISSUE TITLE
Testing Notifications

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#370]
1. Create a script to anonymize the db from beta (prod) -> dev (avoid mistakenly sending emails to users, among other things), can just reuse Elise's script to create a db sample here
2. Add a "SEND_ALL_MAIL_TO" flag in order to redirect emails to the tester's account
3. Add a "MAIL_FREQUENCY_MIN" env variable that will be set to 60 for prod (and by default) but can be set to e.g. 1 for speed of testing
4. Add unit tests to the CP notifications

Test notifications for
- Mention in comments (make a comment mentioning a few users)
- Resolution (Resolve a question I predicted on)
- Significant movement on predicted question (artificially add 100 forecasts of 0 to a question that's ~1 that I predicted on)
Follow a question and test:
- Notifications for every 3 new comments
- Warn on small CP changes
- Artifically advance lifetime and check milestone notification
- Check specific time notification for e.g. 2 minutes from now

**Comment by SylvainChevalier** [comment]
@George3d6 

Missing:

- Status change on question I follow (e.g. in-review→upcoming or open→close).
- Question opens in tournament I follow.

**Comment by George3d6** [comment]
Ok, will do those 2 as well :)

Curious how easy I'd be to automate all of these as part of the integration tests but my hunch if "pretty hard"

**Comment by George3d6** [comment]
Comment notifications work

**Comment by George3d6** [comment]
Open/Close/Resolve work
CP change works
New comments on followed questions don't send notifications.
New questions in followed tournaments don't send notifications.

**Comment by George3d6** [comment]
@hlibowski I don't see a very easy fix/solution for:
1. Notifications being sent on posts you follow when a certain nr of unread comments appear
2. Notifications being sent when a new post is opened in a tournament you follow

Could you look into these 2 + add unit tests for them ?
