### ISSUE TITLE
"An error has occurred when rendering the feed card..."

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#376]
## Current behavior
`s.aggregations is undefined` - appears here and at least once more, three cards later
![image](https://github.com/user-attachments/assets/e1731d49-e243-4b40-9cd6-1592f27a6e02)

Reported by @Tommetaculus

**Comment by SylvainChevalier** [comment]
Should have been fixed by recent performance improvements.

**Comment by Tommetaculus** [comment]
Confirmed! It works for me now.
