### ISSUE TITLE
Add headless chrome to the docker container for Heorku to generate image previews

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#380]
We need to figure out the exact install sequence.

<Also: Implement cache invalidation every 6 hours with some random variation>

**Comment by George3d6** [comment]
Current issue looks something like this:

A better approach then generating these in next is generating them on the BE (allows for proper caching and also allows us to use the same browser driver as we use for unittests)

- Puppeter doesn't work for python (library is deprecated, recommendation is to use playwright)
- Playwright doesn't support alpline linux
- Our current build process fials if I switch to a debian image in odd ways ([see this dockerfile](https://github.com/Metaculus/metaculus/blob/8681ca9d6ca5b9bf353945b8cf86ae296c69100e/Dockerfile)) - i.e. sentry auth token fails to be sourced at build time and/or certain FE files in `/services` are registered as missing at build time

**Comment by George3d6** [comment]
Update: Using the old docker file also results in the docker build failing...

**Comment by elisescu** [comment]
Added a separate service to take screenshots, and updated the main project to use it for generating images of graphs for social media previews, and emails
