### ISSUE TITLE
`t is undefined` when I update my prediction multiple times

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#390]
## Current behavior
Reported by Temet. I reproduced:
![image](https://github.com/user-attachments/assets/255f3fb6-1af2-440f-95ce-c104041ff819)

If I refresh I see that my prediction was actually saved.

https://beta.metaculus.com/questions/737/spacex-mars-mission-by-2030

**Comment by George3d6** [comment]
looks like a translation string error somewhere (?) But I can't replicate this, @ncarazon assigning this to you but unless you have an intuition about what it could be leave it on the backburner until more users report it (and hopefully we capture what's happening via sentry)

**Comment by hickman-santini** [comment]
I could replicate it, at least a couple days ago when Temet reported it.
Maybe someone fixed it. I'll take another look.

**Comment by ncarazon** [comment]
@hickman-santini were you able to replicate it again?

**Comment by hickman-santini** [comment]
No, I haven't seen it again. I'll close!

**Comment by hickman-santini** [comment]
No, I haven't seen it again. Thanks! Closing!
