### ISSUE TITLE
Columns are missing from tournament leaderboards

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#393]
Tournament and Question Series leaderboards should have the columns:

- legacy scoring: Rank, Forecaster, total Score, avg. Coverage, Take, %Prize, Prize
- current scoring: Rank, Forecaster, total Score, Take, %Prize, Prize

(Of course, the "Prize" column will be all 0s for question series and when the prize pool is 0$.)

We should simplify, but it can come later.

P.S.: while you're in there, consider making the columns {rank, score, take, %prize, prize) either monospace or `font-variant-numeric: tabular-nums;`.

**Comment by lsabor** [comment]
done, closing
