### ISSUE TITLE
@ Usernames should link to profiles

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#395]
- When typing `@` in a comment box and writing > 2 letters we should be filtering through a list of user profiles to find usernames that match and show a list to the user (If this is hard i.e. takes > 2 hrs this is low priority and can be ignored for now)
- When there's an `@` mention in the comment this should be replaced with a hyperlink to the user's profile i.e. `@foo` becomes `[@foo](/profile/id_of_foo)` (this should be faster to do and is higher priority)

**Comment by ncarazon** [comment]
The first bullet poit will take more than 2 hours. It requires implementing a custom plugin for mdx editor. 

Regarding this one:

> When there's an @ mention in the comment this should be replaced with a hyperlink to the user's profile i.e. @foo becomes [@foo](/profile/id_of_foo) (this should be faster to do and is higher priority)

@hlibowski as far as I can see, right now BE doesn't return any meta information so we could populate mention links, so there is no way to represent a link with valid user id

**Comment by SylvainChevalier** [comment]
> The first bullet poit will take more than 2 hours. It requires implementing a custom plugin for mdx editor.

That's a medium-big loss, but can happen after launch. I'll spin it in its own issue.
