### ISSUE TITLE
Migrate slider positions

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#399]
When loading a question I've only predicted on www and not on beta yet, the prediction sliders are in default positions. They should be in the position on my last prediction.

Ditto for continuous questions - need to migrate the CDFs from www. Sylvain wrote a mapping for this; @lsabor ask Sylvain if you're not sure what to do here.

**Comment by George3d6** [comment]
This basically means we need to migrate the existing forecasts from Metaculus into slider position

**Comment by SylvainChevalier** [comment]
For binary and multiple choice it should be straightforward.

For continuous, I've put maths [here](https://www.notion.so/metaculus/Formulas-e6c51328ebca4def927a842463b6c459?pvs=4#a16995c2461748a48f5311f1e4871ba9). Summarising here to save you a click:

Define the positions of the sliders as a number in $[0, 1]$, where 0 is “all the way to the left” and 1 is “all the way to the right”. Let’s call the left, center and right positions $l$, $c$, and $r$ respectively. Let’s call the mode, scale and asymmetry parameters $m$, $s$ and $a$ respectively (I believe they are `x0`, `s` and `a` in the old database). Then, for any distribution component:

$$
\begin{align*}
c =& {1 \over 2} + { \tanh((2m-1) \tanh(1)) \over 2 \tanh(1)} \\
l =& c + {a - 1 \over 2} \tanh(s^{1 \over 1.9}) \\
r =& c + {a + 1 \over 2} \tanh(s^{1 \over 1.9}) \\
\end{align*}
$$

**Comment by lsabor** [comment]
completed. closing

**Comment by lsabor** [comment]
Seems like it's still a problem (probably didn't happen last data migration). Reopening to verify
