### ISSUE TITLE
Unread comment functionality is missing

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#404]
- Read and unread comments should be differentiated. A simple highlight would be enough, see e.g. [here](https://www.figma.com/design/EnM7OUVQ0Vo7AYTI3VwaPK/Comments?node-id=17-3281&t=HqYLXud91vj08gWJ-4).
- Viewing the comment should mark it read. If too hard: visiting the question page marks all comments read. 
- The counter in the feed tiles should give unread comments, not total comments.

**Comment by George3d6** [comment]
@hlibowski will handle the backend.
