### ISSUE TITLE
Resolution diamond corresponds to the wrong date

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#413]
## Current behavior
I resolved this just now with resolution date/time of Sep 4 10:22 AM, but the diamond shows up on August 28.
![image](https://github.com/user-attachments/assets/56a58d4f-7253-409f-9a56-b7a6ef68e227)

## Expected/desired behavior
The diamond should show on the day the resolution was known, and potentially the community prediction should be cut off at that time? @SylvainChevalier can you confirm desired behavior here.

**Comment by SylvainChevalier** [comment]
I see two issues:
1. The "actual close time" failed to be set to the resolution time.
2. The diamond doesn't match any of the question's dates.
![image](https://github.com/user-attachments/assets/7278e1ae-1d53-4e79-8bb1-bceec1b109bf)

**Comment by hickman-santini** [comment]
Something is still weird @hlibowski like [this one](https://dev.metaculus.com/questions/7596/) I just resolved with resolution time today (Sep 13) 4PM but it appears as though the diamond is on Aug 12. This is on dev:
![image](https://github.com/user-attachments/assets/dd9583b3-56da-45e6-97dd-44436181fa82)

Also there it says resolved Nov 25, 2025? That's extra weird. 
![image](https://github.com/user-attachments/assets/9c0891d4-e461-4058-a697-e6bed105054c)

Wait a minute.... when I went back to dev.metaculus.com/questions/7596 just now the resolution diamond had moved! Now it looks right. :fearful:

**Comment by George3d6** [comment]
@lsabor can you look at this, it looks like the resolution to datetime conversion is probably wrong (?)

**Comment by lsabor** [comment]
It seems like the resolution diamond has appeared on top of the most recent CP. Simple fix - on it

**Comment by lsabor** [comment]
I've fixed this issue, so closing.
There is another issue, probably not blocking, where the "resolved at" time for group questions is messy. It might require (at least for now) adding `actual_resolve_time` to the Post object.
