### ISSUE TITLE
Show my forecast on closed-not-resolved question card

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#414]
## Current behavior
If you've made a forecast on a question and it's closed, your prediction doesn't show up on the card on main feed, e.g. this one for draaglom:
![image](https://github.com/user-attachments/assets/3d8ecea2-4e0b-43db-8654-aea1c7b045eb)

## Expected/desired behavior
Your prediction (orange curve) should show up on the card.

Reported by draaglom

**Comment by George3d6** [comment]
duplicate
