### ISSUE TITLE
Circles for 'your predictions' on multi-choice don't always correspond to the colors of the options

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#415]
## Current behavior
E.g. draaglom's predictions here (yellow circles should be red):
![image](https://github.com/user-attachments/assets/c66b06eb-d1e3-442e-afa6-45ed22639ac3)

**Comment by ncarazon** [comment]
This is a duplicate of https://github.com/Metaculus/metaculus/issues/385 and should be fixed on dev. 

@George3d6 the fix was merged on September 4th. Have we updated the beta since then?

**Comment by hickman-santini** [comment]
Confirming this looks to be fixed.
