### ISSUE TITLE
Track record data issues

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#419]
A bunch of data and maths issues with the track records. If not specified, issues impact both the user track record and the global track record:

Calibration curve:
- The perfect calibration seems vertically misaligned. E.g. the first bin is 0%-5%, so its center is 2.5%, so the perfect calibration live should be at 2.5% vertically. Maybe the maths are using the bin right edge instead of the bin center?
- Idem for the perfect calibration confidence interval I assume.

Score scatter plot:
- The x axis is hours. I also suspect the circles are not plotted by the right value on the x axis. It should be scheduled close time.
- The line should be an average of all the scores so far (it may already be, but it's hard to tell given the broken x axis).
- The user track should use Peer scores, the global track record should use Baseline scores.

Score histogram:
- The question count and average score numbers seem to be placeholders.
- The user track should use Peer scores, the global track record should use Baseline scores.
- For the global track record, maybe try bumping the CI to 95% or higher and report what that looks like? Currently the CI is so close to the center value that it's not useful at all.

**Comment by lsabor** [comment]
This is complete. Closing. another round of QA on the track records should happen, but the specific issues in this ticket are addressed.
