### ISSUE TITLE
The track record is missing a bunch of copy

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#420]
To be added by me.

**Comment by hickman-santini** [comment]
**Text to add:**

Right above "Calibration curve" header:

> A user's personal track record shows all binary questions on which they made predictions. Like the [Metaculus track record](https://www.metaculus.com/questions/track-record/), you can use it to keep track of success over time. The absolute and peer scores depend on all predictions made before each question's close.

> Each point is displayed at its average value over the lifetime of the question, and, if the prediction has changed, it is spread across multiple bins in the histogram and calibration plots. 

Also add the score definition. The track record page **only** takes into account binary questions, is that right @lsabor? So we just need to add discrete log score definition?

> Discrete log score is used for binary questions, and also continuous questions that resolve out of bounds that are interpreted as binary questions. For a forecast with probability P, the log score is computed as S=log_2(p)+1 if the event occurred, and S=log_2(1-p)+1 if not. Higher scores are better, and a maximally-uncertain prediction P=0.5 gives S=0. 

Maybe put "Each point is displayed..." and score definition in an expandable box (default hidden) called "More details," or something. @lsabor use your discretion!

**Comment by hickman-santini** [comment]
Also, for Score Scatter Plot: The trend line is a time-decayed average: each question is weighted 5% less for every question resolved afterward. 

![image](https://github.com/user-attachments/assets/33c81256-c04a-4464-9c0f-63071ab774bf)

**Comment by lsabor** [comment]
>The track record page only takes into account binary questions, is that right @lsabor? 

No, the calibration curve only takes into account binary questions, but scatter plot and histogram are everything

**Comment by lsabor** [comment]
>we just need to add discrete log score definition

I don't think the score description belongs here, instead I'll just link to the baseline or peer section of the scoring FAQ

**Comment by lsabor** [comment]
@hickman-santini ready for QA - might have to be manually pushed to a deployed to view it "in action", so I'm attaching some screenshots here.
![image](https://github.com/user-attachments/assets/d6f5461b-df05-4ec8-a79e-8137cd6aa0fa)
![image](https://github.com/user-attachments/assets/5640b586-2890-4c9c-9536-ac16fea1ed2b)

And:
![image](https://github.com/user-attachments/assets/d1d44e3d-2908-4cf6-8359-5337b10e6e63)
![image](https://github.com/user-attachments/assets/c1c12f73-b85b-46d4-a778-731c9e651aa9)

**Comment by lsabor** [comment]
>The trend line is a time-decayed average: each question is weighted 5% less for every question resolved afterward.

not currently. I'll add that in later if we change the trend line calculation

**Comment by hickman-santini** [comment]
- Remove "The three parts displayed below..."
- Agree with your decision to link to the FAQ for the scores and coverage explanations, thanks!
- Too much space between "Hover over a circle..." and "The Score Scatterplot..."
- Edits to the calibration curve explainer (@SylvainChevalier will almost certainly have more edits, but in the meantime):

> The Calibration Curve takes into account forecasts on binary questions only. The x-axis shows prediction ranges (e.g., 17.5% - 22.5%) and the y-axis shows the actual "Yes" resolution rate for questions within each range. Yellow diamonds represent these observed rates. The gray lines along the diagonal (y=x) are what you would get by forecasting the "true" probability on a large number of questions. The shaded area is the 90% credible interval around the perfect calibration, the width of which depends on how many questions the forecaster has made in that x-axis range. If the forecaster had been perfectly calibrated, the diamond would have been in that range 90% of the time.

**Comment by hickman-santini** [comment]
Made a new issue for the overview page: https://github.com/Metaculus/metaculus/issues/739
