### ISSUE TITLE
String errors should show up as soon as you leave a text entry box

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#424]
## Current behavior
It's not until you submit a question that string errors are flagged:
![image](https://github.com/user-attachments/assets/13cfa4dc-82ff-43e8-8e2d-c633bc3005d9)

## Expected/desired behavior
It would be great if the string errors could show up before you click submit when creating a question. They do on prod when you click out of the text box into another field (would be ideal if they showed up during typing though).

**Comment by hickman-santini** [comment]
@ncarazon just make this say **String must contain at most 200 characters**

![image](https://github.com/user-attachments/assets/02a8d8bb-2124-4d64-a9b6-6de5a10054ff)

**Comment by ncarazon** [comment]
Ready for testing on dev
