### ISSUE TITLE
Error when I save forecasts then refresh on group

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#439]
## Current behavior
On presidential [election](https://dev.metaculus.com/questions/11245/) question:
![image](https://github.com/user-attachments/assets/132b5dc9-728c-4502-b83d-b033914fd826)

When I clicked try again it was fine, my forecasts had actually been saved, so I'm labeling medium. Shouldn't be blocking but if you can tell what happened (via sentry)...? It didn't error on the next group question I tried. @George3d6 

This is on dev.

**Comment by lsabor** [comment]
I don't think this happens any more - very old ticket.
closing as complete
