### ISSUE TITLE
Notebook have extra `\n`s

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#444]
Notebooks have extra line feeds.
Compare [www](https://www.metaculus.com/notebooks/27612/experimenting-with-minitaculuses--collaborate-with-us/):
![image](https://github.com/user-attachments/assets/c09df438-deed-4b4c-9f89-ae70f5d625fa)

And [beta](https://beta.metaculus.com/notebooks/27612/):
![image](https://github.com/user-attachments/assets/9f70c6c9-3c7b-45b6-94ba-1049af35a629)

If I manually remove the line feeds from the notebooks on beta, it looks correct:
![image](https://github.com/user-attachments/assets/4794bf00-4816-4577-8f4e-79c70e522c71)

**Comment by ncarazon** [comment]
@hlbmtc looks like this is a migration issue. BE returns redundant `\n`s

**Comment by hlbmtc** [comment]
Fixed
