### ISSUE TITLE
Can't update project of the question

### ISSUE THREAD

**Issue by hlibowski** [Metaculus/metaculus#445]
## Current behavior
Frontend does not send updated projects/tournamens to the backend during post update
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b3874844-7847-446d-bee8-850a0debe66e">

Please check creation behaviour as well

**Comment by ncarazon** [comment]
@hlibowski 

I believe there is a problem on the backend side. The data sent from the frontend correctly contains the `default_project_id`.
However, it is not set in the object we receive back from the backend after update or create actions.
I suspect this issue might be specific to certain tournaments. For instance, it works correctly with projects like "Ukraine Conflict" or "Verity," but when I select "AI Benchmarking Pilot," the default "Metaculus Community" is set on the server.

![image](https://github.com/user-attachments/assets/8301ba5d-0412-4c8a-9e21-14530b6dc0cd)

![image](https://github.com/user-attachments/assets/76a36e33-5463-468e-943a-690a33de4591)
