### ISSUE TITLE
Make one of our FAB bots participate on beta.metaculus.com

### ISSUE THREAD

**Issue by elisescu** [Metaculus/metaculus#456]

**Comment by hickman-santini** [comment]
@ncarazon is this something you could do? If not, can you suggest another engineer?

**Comment by ncarazon** [comment]
@hickman-santini I think @hlibowski or @lsabor would have more context here

**Comment by hickman-santini** [comment]
Elis did this! The bot is working now, thanks @lsabor for helping Tom.
