### ISSUE TITLE
Server error on profile

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#466]
When I click on my profile (`sandman` fwiw - https://beta.metaculus.com/accounts/profile/139400/):
![image](https://github.com/user-attachments/assets/d4b08d6e-c5aa-460d-9a77-688cadbd338a)

**Comment by SylvainChevalier** [comment]
I've seen this, was performance issue in my case. What happens when you reload?

**Comment by ncarazon** [comment]
@hlibowski Looks like BE issue. `/api/users/<id>` endpoints results in the following error for profile `139400`:

```
ValueError: Out of range float values are not JSON compliant: nan
```

**Comment by George3d6** [comment]
This looks resolved testing local, dev and beta
