### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#467]
**Running list of lagginess complaints, quotes:**

1. If I try to unfollow notifications the UI reaction time is very very
 slow. I thought the Unfollow button was doing nothing at all at first. **Here is a screencast how it looks for me: https://upload.kikeriki.at/file_share/paWGzJXam_nWVVGZz61vf5P6/metaculus-follow.mp4** (user: `t.b` - reported at 6:17 PM Eastern Sep 9)
2. I also experienced extremely long UI delays when trying to change the
language. I think it was a full minute. It really feels like the
buttons are not working at all. (`t.b` - ditto)
3. The question details / resolution criteria / background info load async and can take quite a while, which degrades the experience a bit. I bet this is mostly because the beta server might be on limited resources. But I thought I'd note it here anyway: assuming a faster prod deploy, it still could be frustrating on mobile, on a poor network, etc. If those could load synchronously that'd be much nicer! [I think @lsabor said it's not a problem of async loading nor resources but this is what `draaglom` said - reported at 5:35 PM Eastern Sep 3]
4. Every new page load (question pages, tournament pages…) was slow for me. Also specific actions such as Following/Unfollowing a question took far longer than before. If before it was around a second per load/action, now it was even 3-5 seconds at times… roughly. (user: `Zaldath` - they had said 2 or 3 times slower - reported at 5:44 PM Eastern Sep 9) _Note: at 11:30 AM Eastern Sep 10 they said they tested it again and everything seemed to work considerably faster :shrug:_
5. "The site feels slower overall." (`skmmcj` at Sep 9 9:30 PM Eastern)

**Comment by hickman-santini** [comment]
Here's t.b's screencast:
https://github.com/user-attachments/assets/6222b8c9-2577-40e9-8044-aff7241ad975

**Comment by George3d6** [comment]
Current results:
- Under stress testing the dev env performs well when resources == prod (i.e. the beta. domain)
- We should make sure our database is large enough
- Current issues look to be quite random and often have to do with data that's already loaded, so I think @ncarazon we should make sure there are no situations in which our next frontend might arbitrarily freeze
