### ISSUE TITLE
New color to replace neon green in question histograms

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#492]
A few people have mentioned this now. Can we use a softer green here? Or pick one of the two colors we use for continuous question distributions?
![image](https://github.com/user-attachments/assets/d69d7374-cb8b-410a-b88b-24ae446e128a)
![image](https://github.com/user-attachments/assets/2c7637c9-c352-4ee4-bdf0-4b9e4eb9ae82)

**Comment by George3d6** [comment]
Surely this does not block the release?
