### ISSUE TITLE
Prepare the old site for after the switch

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#493]
After we switched to the rewrite, we'll keep the old site running:

- at old.metaculus.com
- with a large visible banner saying "this is an old obsolete version, any action you take here will not be migrated to the new version".
- not sending any emails.
- anything else?

The banner, and email suppression, should only apply to the main subdomain (currently at www), not to any subdomains like eurasiagroup.metaculus.com or forpol.metaculus.com.

**Comment by George3d6** [comment]
cc @casens5 do you think you could do the changes here ? @hlibowski can help with the DNS

**Comment by George3d6** [comment]
We should point old.metaculus.com to it already and have the banner announcing the release date

**Comment by hickman-santini** [comment]
Notes from rewrite sync just now:

- There will be some amount of time when the site is unavailable while we make the Final Db Dump - prob around two hours
- **Tentative Plan:** Once we've closed the high-priority issues that are open right now, we'll do one more round of concerted internal QA and then put up the banner saying "we're launching the new site on x day, site will be ... from [time] etc"
- @hlibowski suggests make DB read-only during transition? 
- @hickman-santini to ask Ryan or Christian what time zones people visit the site from so we can choose best time for site to be "down"
- @George3d6 what time zone are you in?

**Comment by hickman-santini** [comment]
@ncarazon create the PR, don't merge it until new site is launched. Thank you!

**Comment by ncarazon** [comment]
@hickman-santini just confirming what should be done from my side in terms of this task: I should add a banner with a similar UI that we have on production with a text, mentioned in the description. The PR should be created for the rewrite repo, not for the production one. Is this right?

**Comment by hickman-santini** [comment]
@ncarazon no, this is for prod which is going to continue to be available at old.metaculus.com. There are a few more pieces of this task in the top description. We just made this issue here rather than on the other repo so we wouldn't forget to track it.

**Comment by ncarazon** [comment]
@hickman-santini I don't have access for the prod repo, so it probably faster for @lsabor to do the banner as well.

**Comment by SylvainChevalier** [comment]
@hlbmtc subdomains that should still use the old codebase for now:

- ai-forecasts.metaculus.com
- ai.metaculus.com
- algebraic-geometry.metaculus.com
- alt-meat.metaculus.com
- bain.metaculus.com
- bethlehem.metaculus.com
- bridgewater.metaculus.com
- colorado.metaculus.com
- covid.metaculus.com
- czea.metaculus.co
- delphi.metaculus.com
- demo.metaculus.com
- ea.metaculus.com
- eurasiagroup.metaculus.com
- ev.metaculus.com
- forpol.metaculus.com
- fortnightly.metaculus.com
- intranet.metaculus.com
- kitson.metaculus.com
- Onebrief.metaculus.com
- pandemic.metaculus.com
- prague1.metaculus.com
- prague2.metaculus.com
- prague3.metaculus.com
- seattle.metaculus.com
- tom2test.metaculus.com
- tomtest.metaculus.com
- uva.metaculus.com

**Comment by SylvainChevalier** [comment]
done
