### ISSUE TITLE
US Elections topic is not working

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#494]
https://dev.metaculus.com/questions/?topic=US_2024 yields "No results found"

**Comment by lsabor** [comment]
The filter is working properly, but for some reason no posts exist for the "US_2024" topic.
Probably requires a edit to the project migrator.

**Comment by lsabor** [comment]
Ok, so "US_2024" is actually only a topic for eurasiagroup.metaculus.com, so it makes sense that it is unpopulated on the main site. I'm not totally sure what the "smoothest" way to automate this is for the rewrite (@hlibowski maybe you have a suggestion), but for now, it bascially shouldn't appear on the Topics sidebar section. The way to do that is to go to the admin panel (/admin/projects/project/15814/change/) and either increment the "order" field until it's greater than 6, or set "Is active" checkbox to false.
It's pretty minor, so I suggest doing one of those @hickman-santini and totally skipping the nuanced migrator changes.

Not closing yet until I've heard from Molly or Hlib on this.
