### ISSUE TITLE
Make the medals clickable

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#496]
> It would be very convenient if the medals in the profiles' Medals section could be clicked in order to directly go to the corresponding tournament/leaderboard. 

E.g. I'd like to be able to click "Breaking News Tournament" and be taken to the tournament page from [Jgalt's medals page.](https://beta.metaculus.com/accounts/profile/101465/?mode=medals)

Requested by Sergio.

**Comment by SylvainChevalier** [comment]
this is fixed.
