### ISSUE TITLE
Date prediction tables have epoch seconds in some fields

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#501]
[Example](https://beta.metaculus.com/questions/3479/):
![image](https://github.com/user-attachments/assets/e714d0c2-4c2c-4d0b-a541-15b693fc4b8d)

**Comment by ncarazon** [comment]
This ticket is a duplication of https://github.com/Metaculus/metaculus/issues/348

As mentioned in comment here, Luke already fixed this: https://github.com/Metaculus/metaculus/issues/348#issuecomment-2343321329

It works fine on dev: https://dev.metaculus.com/questions/3479/

**Comment by SylvainChevalier** [comment]
Sorry, I should have checked on dev.
