### ISSUE TITLE
Fan graphs are broken for binary groups

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#503]
[Example on beta](https://beta.metaculus.com/questions/11480/):
![image](https://github.com/user-attachments/assets/6106fedc-0598-46e0-983f-ae64132b5778)

[On dev](https://dev.metaculus.com/questions/11480/) it's completely blank:
![image](https://github.com/user-attachments/assets/b750f5c7-5103-4512-b0bb-b4ac88adc8ec)

**Comment by SylvainChevalier** [comment]
@ncarazon if you don't have anything higher priority this would look super nice for launch.

**Comment by SylvainChevalier** [comment]
lgtm, thanks @ncarazon!

**Comment by SylvainChevalier** [comment]
Oops, missing from the feed tile and embed, e.g. [this one](https://www.metaculus.com/questions/11480/chinese-invasion-of-taiwan/):
![image](https://github.com/user-attachments/assets/d2770579-7957-4728-85ed-1557279a8f77)
![image](https://github.com/user-attachments/assets/5769575f-32b1-48a2-a49e-cf5dd56d8a1c)
![image](https://github.com/user-attachments/assets/59576158-e80b-478a-9508-abe04c7b0e68)

**Comment by SylvainChevalier** [comment]
Also the resolution diamonds are wrong.
E.g. [this question](https://www.metaculus.com/questions/13125/russian-nuclear-tests-20222024/), 2023 resolved No so the resolution diamond should be aligned with 0% (if it had resolved Yes it should be aligned with 100%).
It's fine to still have the community prediction square to its last value (here 5% apparently).

![image](https://github.com/user-attachments/assets/4a08e34e-f8d1-4f4a-8f4a-b747ca6b5b6e)

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
