### ISSUE TITLE
CP shouldn't be populated on numeric questions until there are forecasts

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#520]
## Current behavior
When you create a numeric question you have this blank space where the graph would be, and when you mouse-over that empty space you get "P(x=?): 0.000 (community)" message. And in not-submitted numeric group questions, a CP is visible when it shouldn't be.

Reported by `skmmcj` who provided this screenshot

![image](https://github.com/user-attachments/assets/0572c0eb-5096-48dc-8667-64d74debd636)

My screen recording from non-group numeric question:

https://github.com/user-attachments/assets/7a4ab7c7-fbc9-4c96-b0f5-1c0eed49c465

## Expected/desired behavior
1. There shouldn't be a "default" CP. If there are no forecasts it should just show `...` (as opposed to the 100s) like "My Prediction" (do you agree @SylvainChevalier). 100 is the max selected my the question creator.
2. I think the mouse-over behavior is probably fine actually.

Another screenshot for good measure; here 80 was my max. There's also something weird in the bottom left corner of the graph but I'm not fussed about it.
![image](https://github.com/user-attachments/assets/e7d8657c-ea20-44c9-a638-2f8a072fbdea)

**Comment by hickman-santini** [comment]
On second thought, this might just be the desired behavior... @SylvainChevalier can you comment and mark this approved if you think it's worth changing.

**Comment by lsabor** [comment]
Here is an example: https://www.metaculus.com/questions/29520/us-covid-hospitalization-forecasts-2024-25/
I think i know the issue. it should be a quick fix.

**Comment by lsabor** [comment]
closing as complete

**Comment by lsabor** [comment]
failed to implement correctly

**Comment by lsabor** [comment]
Ok fixed
