### ISSUE TITLE
404 when you create a group question with field missing from a subquestion

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#521]
## Current behavior
If you try to create a group question with a field missing from a subquestion (e.g., close date, subquestion label), it lets you submit (click "Create Question") but then it 404s

## Expected/desired behavior
Don't let someone submit before all the fields are populated. If they click "Create Question," have red text like this pop up for empty subquestion label or close or open date.
![image](https://github.com/user-attachments/assets/14620dd1-4e4f-4ef7-a058-cb26178b8466)

**Comment by lsabor** [comment]
This was fixed at some unknown point. closing as complete
