### ISSUE TITLE
Suggest usernames when typing @ in comment

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#538]
When typing @ in a comment box and writing > 2 letters we should be filtering through a list of usernames to find usernames that match and show a list to the user.

Looked like this in old codebase, feel free to make it look better:
![image](https://github.com/user-attachments/assets/309e7272-67e9-4b04-bac3-2fc8ad10bf81)

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by ncarazon** [comment]
That's doable. I'll implemented it in a way when mentions list is populated with usernames of people who have commented on the question until the user triggers BE request to search (input query is > 2 symbols)

**Comment by ncarazon** [comment]
The latest changes are available for testing on dev

**Comment by nangchrys** [comment]
Some comments:
- author usernames should be included in the mentions list
- I see this bug occasionally, where the link to the user is displayed, but it's not clear to me what causes it
![image](https://github.com/user-attachments/assets/6c75f31d-b892-493d-a682-7c261cc958e1)
- it'd be nice if the mentions list was sorted so it started with the names that begin with what I've written (e.g. `@ryanb` should list RyanBeck before bryanbaran).
- Occasionally if I write `@ryanb`, go down to the menu and press tab on RyanBeck, I get `@ryan@Ryanbeck`. Also when this happens ctrl+A and backspace deletes only the first character.
- if I try to select a tagged username in the comment box (either by dragging my cursor over the username or pressing shift+up), my cursor disappears and stops working. I have to click the comment box again for it to work.
- currently selecting a username automatically enters a space after I press another character, but this is not shown before. That is: I write out @ and then nangchrys, I press tab and I see `@nangchrys|`, I press "a" and I see `@example123 a|`. But I instinctively press space after `@nangchrys|` and end up with two spaces.

**Comment by nangchrys** [comment]
> Do you mean question authors? We already populate the list with comment authors and it seems to work correctly, so want to double-check

Yes, comment authors seems to work correctly to me too.

> Could you share a link to comment where this was reproduced?

Here are some: [one](https://www.metaculus.com/questions/30297/will-nvidia-have-the-largest-market-cap-at-the-end-of-2024/#comment-230753), [two](https://www.metaculus.com/questions/29900/bitcoin-dominance-630-on-any-day-in-novdec-2024/#comment-228899), [three](https://www.metaculus.com/questions/29028/us-state-dept-global-arms-sales-approved-q4-2024/#comment-228941), [four](https://www.metaculus.com/questions/29028/us-state-dept-global-arms-sales-approved-q4-2024/#comment-228962). I've only seen it happen when the tag is created by the reply button, but these are also more frequent so I'm not sure. Also I think it's visible when it happens, i.e. if the user is paying attention they can see and delete the extra link and it works fine.

> I wasn't able to reproduce it. Could you share which browser and OS you're using? Also, it would be very helpful if you could record a screencast (maybe there are some specific pre-conditions when the issue appears)

Firefox on Windows. It doesn't happen always, here it happens twice I think, once in the beginning and once in the end. You can see my attempt at deleting it by ctrl+A & backspace repeatedly.

https://github.com/user-attachments/assets/9bc563a2-97a4-4aa6-a465-bee86c93f95d

**Comment by nangchrys** [comment]
Also another bug. Steps to reproduce:
1. Click reply in a comment.
2. Click in the comment box, it shows this
![image](https://github.com/user-attachments/assets/174ed8fb-db7b-404b-9962-0a81aeba3b51)
3. Without typing anything click outside the comment box. It shows this
![image](https://github.com/user-attachments/assets/88a80e9b-bfb6-4153-b581-85fa82177c3a)
4. Click in the comment box again and try to type. Nothing happens.

**Comment by ncarazon** [comment]
Deployed fixes to the dev environment. Some key updates: mentions are now displayed as plain text in edit mode rather than being formatted as markdown links (similar to how GitHub handles it). This change resolves the conflict between the mentions plugin and the editor’s native link plugin. It also provides a more scalable solution, as mentions will be stored as regular links in the backend. This approach eliminates dependency on the profile page’s URL schema on the client side.

Regarding the following point:

> f I try to select a tagged username in the comment box

Adding proper styling for a focused mention box in edit mode would require significant effort. The reason is that the mentions package we use is not fully supported by the MDX Editor. The plugin’s theming API isn’t compatible with the editor, so we’d need to implement a custom patch for the package. Given this, I assume this option is not critical. However, let me know if we should prioritize it. We can either include it as part of this high-priority ticket or create a separate, lower-priority task for it.

**Comment by nangchrys** [comment]
Everything seems to be working great and the remaining issue is definitely low-priority. Thanks!

**Comment by SylvainChevalier** [comment]
@nangchrys could you put the remaining issue(s) in a new ticket? I'll close this one.

**Comment by ncarazon** [comment]
Tracking here: https://github.com/Metaculus/metaculus/issues/1597
