### ISSUE TITLE
Revive the "My Participation" filter options

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#571]
It seems judging by https://github.com/Metaculus/metaculus/issues/299 that we had implemented this at one point? Where did it go?

Would like to have these options from prod on beta:

![image](https://github.com/user-attachments/assets/fd09ff17-bd60-4e69-b7f0-a06ad7c4db18)

**Comment by hickman-santini** [comment]
You can do this from the left sidebar (My Predictions) but at least two people have not noticed that in the sidebar and asked for it to be a filter, so:

Let's just add a My Participation: Predicted/Not Predicted filter (leave out Authored, Upvoted, Moderating). (Discussed in sync)

**Comment by ncarazon** [comment]
@hlibowski or @lsabor I've [added](https://github.com/Metaculus/metaculus/pull/611) new options to filter pop-up, but looks like `not_forecaster_id` param doesn't work and it still returns questions with user forecast. Could you, please, take a look?

**Comment by lsabor** [comment]
On it

**Comment by lsabor** [comment]
@ncarazon I added support for `not_forecaster_id` I'm passing this back to you to close it out if you've finished your part.

**Comment by ncarazon** [comment]
@lsabor I checked on localhost and still seems to return questions with forecasts for group posts:

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/597f24ab-cb84-4304-b190-7b6cc920c3d6">

**Comment by lsabor** [comment]
Our of curiosity, did you not forecast on at least 1 of the subquestions?

**Comment by ncarazon** [comment]
There is a forecast from my user:

<img width="872" alt="image" src="https://github.com/user-attachments/assets/6ded043a-4dda-4009-bf8c-2a67519bf443">

And filter `not_forecaster_id` should exclude such posts from the feed, no? It seen to work correctly for the rest of question types

**Comment by lsabor** [comment]
Yup, my bad. I missed it in the PostFilterSerializer. Just pushed a fix

**Comment by lsabor** [comment]
>And filter not_forecaster_id should exclude such posts from the feed, no? It seen to work correctly for the rest of question types

I think the answer to that is no. I'll be discussing it with Molly today, but filters like this make the most sense as "if any" rather than "all" in general.

**Comment by ncarazon** [comment]
> Yup, my bad. I missed it in the PostFilterSerializer. Just pushed a fix

Yep, work fine now, thanks!

**Comment by hickman-santini** [comment]
Lovely
