### ISSUE TITLE
Remove y-axis label from score histogram

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#573]
## Current behavior
Both axes are labeled "Person's Peer Score"
![image](https://github.com/user-attachments/assets/8d890d92-f9f7-4947-961b-98ee516e10ac)

## Expected/desired behavior
Histograms don't need y-axis label, although we should say how many/which questions are factored in here (is it most recent 42 questions?) -- add that as a note under the graph.

**Comment by lsabor** [comment]
fixed - closing
![image](https://github.com/user-attachments/assets/c1f77210-7b80-4efa-9540-661365524699)

**Comment by lsabor** [comment]
>(is it most recent 42 questions?) -- add that as a note under the graph.
this was a placeholder number for a while before actually calculating anything, so it has no bearing
I think "Count" should suffice along with the context of it being a "Histogram".
Feel free to request tweaks, but id recommend doing so in another ticket with "simple" and "low priority" labels

**Comment by hickman-santini** [comment]
@lsabor sounds good to me, although let me make sure I understand -- the histogram does use *all* the questions a user's forecasted on now, not like a most recent window?
