### ISSUE TITLE
Close date is only there for some cards on main feed

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#576]
## Current behavior
On beta this is what it looks like... and on dev it seems _no cards_ have close date.
![image](https://github.com/user-attachments/assets/2033bfb2-cabd-4b9d-96e2-8264c0e8d5d7)

## Expected/desired behavior
Every card should have that little radial lifetime indicator and "Closes [date]"

**Comment by lsabor** [comment]
closed as complete
