### ISSUE TITLE
Migrate AIB demo page

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#590]
Currently broken on prod: https://www.metaculus.com/aib/demo

Not blocking but I think should be pretty high priority after launch

**Comment by lsabor** [comment]
This is a heavy lift. It's not just a static page, but an interactive demo with calls to endpoints we haven't set up in the rewrite.

Elis is the only remaining eng who worked on the original. @elisescu Would you be able to work on bringing this to life in the rewrite?

**Comment by elisescu** [comment]
I don't think we need this page. We briefly discussed it a while ago when I was porting FAB stuff and agreed not to invest time in it. Closing the issue.
