### ISSUE TITLE
Weird graph on card for one question group but not others

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#597]
## Current behavior
On biosecurity tournament page: https://beta.metaculus.com/tournament/biosecurity-tournament/?status=open
![image](https://github.com/user-attachments/assets/133e34b7-13b4-45b4-89d8-7f4327aa41f6)

When you go to the question the graph is right.

But there's at least one question group that is normal on beta, on the same feed:
![image](https://github.com/user-attachments/assets/251f92e2-8e0f-4142-ab89-4c3d68a76415)

What's the difference between these questions?

## Expected/desired behavior
On prod:
![image](https://github.com/user-attachments/assets/810dd192-fcec-4261-b015-0b25f5a22df6)

Reported by `oldwindways`

**Comment by hickman-santini** [comment]
Just noticed that "Biosecurity Tournament" is also missing from the cards on beta.

**Comment by lsabor** [comment]
>Just noticed that "Biosecurity Tournament" is also missing from the cards on beta.

I'll try and fix this, but if it's not trivial ill move it to another ticket

**Comment by lsabor** [comment]
Turns out the timeline never checked if this was supposed to display as a fan graph. I've bandaided it, but definitely experiencing some tech debt in this area...

I'm moving the missing chips to another issue.

**Comment by lsabor** [comment]
closing as finished
