### ISSUE TITLE
Swap greys in legend for calibration graph

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#598]
Just need to swap the colors on perfect calibration and perfect calibration CI. I think it's pretty self-explanatory as-is, but might as well.
![image(14)](https://github.com/user-attachments/assets/9d0631ca-1fc9-4bb7-8d82-8b899e7e9a59)

Reported by `oldwindways`

**Comment by lsabor** [comment]
nice catch, sure I'll flip it

**Comment by lsabor** [comment]
completed, closing
