### ISSUE TITLE
FAQ says you can use space bar to force symmetry (numeric questions)

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#600]
We should either change the FAQ or implement the space-bar thing. Currently the space bar does the normal thing of scrolling down the page a bit. I don't mind if we just change the FAQ; I haven't heard from anyone else that they miss the force symmetry feature.

From oldwindways:

Is the ability to force a distribution to be symmetrical not supported in the new version?  It appears in the FAQ still (https://beta.metaculus.com/faq/#range-interface) but my quick test did not seem to work.

> **Asymmetric Predictions**
> The probability distributions can be entered asymmetrically by dragging one side of the distribution slider. On desktop computers users can hold the shift key while dragging a slider to force the distribution to be symmetric.

**Comment by hickman-santini** [comment]
Can whoever takes this issue also just do a pass over the FAQ for any other features that don't exist on the new site.

**Comment by lsabor** [comment]
done - completed

there never was any reference to the symmetry feature in the FAQ, so I made no adjustment there. We may want to add symmetry back in, so I'll make another low priority ticket for it.

**Comment by hickman-santini** [comment]
It definitely is in the FAQ: https://beta.metaculus.com/faq/ "Asymmetric Predictions"

**Comment by lsabor** [comment]
Missed that - correct

**Comment by ncarazon** [comment]
Is there anything else we need to do besides removing the mention of the symmetry feature? @lsabor I assume you checked the rest FAQ content, right?
