### ISSUE TITLE
If I user is in the top 10, just highlight them

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#601]
Like Zaldath in sixth place here, weird that they're shown in baseline accuracy twice instead of just highlighted in sixth place:
![pic](https://github.com/user-attachments/assets/2c4bea17-2db2-4edd-8c94-0822e756d0ab)

**Comment by casens5** [comment]
i disagree, i think the user column should always exist (if that user has any data to be ranked in that category/year), and the user row should also be highlighted.

**Comment by PatMyron** [comment]
For some reason lbiii is highlighted?
<img width="400" alt="Screen Shot 2024-10-07 at 2 11 44 PM" src="https://github.com/user-attachments/assets/c04b1261-2760-4e93-9b2f-00a888e78769">

**Comment by lsabor** [comment]
Most of this is fixed.
Highlighted rows now only show exclusions. e.g. "Recency Weighted CP" shows up as highlighted, and is exlcuded from taking a rank away from anyone else, though is shown on the leaderboard.
User's row is not highlighted in any way in-context, though the user's row always shows separate from the general table.
I'll add that simple highlight and close this ticket.
