### ISSUE TITLE
"Copy link" for question from a group should highlight it in the forecast maker

### ISSUE THREAD

**Issue by ncarazon** [Metaculus/metaculus#616]
## Current behavior
Having `sub-question` doesn't visually highlight the selected question on forecast maker

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/6769ee73-5fbe-4b1d-afc7-8adb8977f1d1">

## Expected/desired behavior
Matching question is first option is a list and has a highlighted state

**Comment by hickman-santini** [comment]
Gorgeous! Closing!

![image](https://github.com/user-attachments/assets/54457ad4-702f-4224-80ee-549f1aabecf0)

![image](https://github.com/user-attachments/assets/1f370d8c-f94f-48cf-b557-dc10e555022e)
