### ISSUE TITLE
Scores dont appear on Group and Conditional questions

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#620]
example
User: LukeAdmin
Group Question:
`/questions/11370/`
![image](https://github.com/user-attachments/assets/75e07210-3cbb-4d73-b468-05c136c86cb6)

Should appear something like: `/questions/1663/`
![image](https://github.com/user-attachments/assets/663d676e-7455-493e-83e5-7326e7c0e8af)

Also worth noting: when the "Additional Scores" drawer is empty, it shouldn't display at all.
Feel free to make tweaks e.g. centering the boxes etc.

**Comment by hickman-santini** [comment]
LGTM!

![image](https://github.com/user-attachments/assets/bd7fc496-5e3b-40ee-9e84-0b9b31a46f1f)
