### ISSUE TITLE
Add unresolve action

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#646]
Back end is completed and hooked into `api/questions/<id>/unresolve`

Front end needs button.

QA will be important as well.

**Comment by lsabor** [comment]
@ncarazon Can I get your help making an "Unresolve" button on the front end? It should appear when the logged in user has resolution privileges and the question is resolved. The end point is already set up to be called by `unresolveQuestion` in `actions.ts`.

**Comment by ncarazon** [comment]
@lsabor Should I add an "unresolve" button for conditional questions? Currently, we don’t have a resolution button for these. If so, should the unresolve function work for the general question (post), or only for conditional or yes/no questions?

Also, at the moment, every unresolve request sent to the backend returns an error. Is this the expected behavior, or do I need to make adjustments to the API call?

```
TypeError: fromisoformat: argument must be str
[26/Sep/2024 16:15:55] "POST /api/questions/13734/unresolve/ HTTP/1.1" 500 164706

TypeError: float() argument must be a string or a real number, not 'NoneType'
[26/Sep/2024 16:15:49] "POST /api/questions/10880/unresolve/ HTTP/1.1" 500 173681

AttributeError: 'NoneType' object has no attribute 'timestamp'
[26/Sep/2024 16:15:47] "POST /api/questions/10847/unresolve/ HTTP/1.1" 500 161813

ValueError: None is not in list
[26/Sep/2024 16:15:38] "POST /api/questions/20676/unresolve/ HTTP/1.1" 500 164883
```

**Comment by lsabor** [comment]
Nope - no unresolve or resolve button for conditionals. They are entirely determined by the resolution status of their parent / child, so nothing needs to be implemented there.

Unresolve should strictly appear anywhere that the "resolve" button would appear.

**Comment by lsabor** [comment]
>Also, at the moment, every unresolve request sent to the backend returns an error. Is this the expected behavior, or do I need to make adjustments to the API call?

I'll look into this. Thanks for implementing the button - that was the blocker for me!

**Comment by lsabor** [comment]
Closing as complete!
Thanks to @ncarazon.
