### ISSUE TITLE
Adding images to comments not working

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#648]
Reported by RuslanBes:

> Uploading images in comments (in the visual editor) doesn't work right now.
> 
> When selecting ther image clicking "Save" button it does nothing and the Network tab shows successful 200 OK POST but with the response body is:
> 
> 0:["$@1",["Xu-yvt-neYf9vwneWGh3B",null]]
> 1:{"errors":{"message":"Unexpected Server Error"}}

Here's what it looks like for me:

https://github.com/user-attachments/assets/eefc1d3b-f1c4-48aa-925f-d11f4a1998fb

Also, if easy: 

> the "Save"  and "Cancel" buttons need some hover effects and on-click reactions or people will happily mash them mercilessly when given a chance.

**Comment by hlbmtc** [comment]
Fixed. Beta example: https://beta.metaculus.com/questions/11332/#comment-191053
