### ISSUE TITLE
Users can forecast on closed and resolved subquestions / conditionals

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#656]
Users are still able to predict on closed and resolved subquestions / conditionals
Both the back end doesn't reject the prediction (which it should), but also the UI allows the input to happen.
Simplest solution is to check the status of each individual subquestion and activate / deactivate the user input accordingly.  @ncarazon 
Back end change should be to validate that a question is open as part of the prediction process. @lsabor

**Comment by lsabor** [comment]
Front end change works properly. I'll add the back end change now.

**Comment by ncarazon** [comment]
Oh, @lsabor, sorry. Forgot about the BE part. I removed the Awaiting QA label

**Comment by lsabor** [comment]
No problem - closing as complete.
