### ISSUE TITLE
Chips don't appear on conditional display

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#657]
![image](https://github.com/user-attachments/assets/01e5abb6-09e0-448d-888f-4cddef730aba)

In this scenario, the parent question was resolved.

This is what it looks like after the child also resolves:
![image](https://github.com/user-attachments/assets/9fe5c769-2383-4cbc-a3cd-7daac54efb94)

The good here is that the "yes" branch is correctly grayed out, and in the scenario where the parent and child question are both resolved we have the correct things displaying and making a prediction is disabled.

the bad:
when the parent question only is resolved:
- it should have the chip showing how it resolved
- the "yes" branch should show "annulled"
- the "yes" branch should not be able to be forecasted on (see issue #656 )

Similarly, if the child question is resolved, both branches should be closed to forecasting and should be indicated as such but are not resolved or annulled until the parent resolves.

**Comment by lsabor** [comment]
@ncarazon I'm passing it your way. Let me know if the API returns require any more info to make this happen. I suspect the issue is that the chip display reads from the Post status, which should be irrelevant in general especially here.

**Comment by ncarazon** [comment]
@lsabor 

> it should have the chip showing how it resolved
> the "yes" branch should show "annulled"
> the "yes" branch should not be able to be forecasted on (see issue https://github.com/Metaculus/metaculus/issues/656 )

I have a question regarding conditional forecasts. For example, if the condition is resolved as "yes", should we annul only the "no" variant and disable forecasts for that option, or should both variants be disabled?
Currently, in production, we remove the  forecast maker at all in such cases.
https://www.metaculus.com/questions/15153/conditional-ukrainian-exports-in-2025/

So I disabled the forecast maker for both options in the rewrite as well

**Comment by lsabor** [comment]
Discussed on a call:
Disabling all forecasting once either parent or child is resolved is the correct solution
Also checking on resolution and actual_close_time is the correct overall approach. `status` can't be guaranteed to correctly report being closed.

closing as complete - nice work @ncarazon
