### ISSUE TITLE
Path traversal vulnerability

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#663]
@hlbmtc can you just give this some thought; may not require action. Just close it if you don't think we need to do anything about it.

Reported by RuslanBes:

Check if you have the [path traversal](https://cwe.mitre.org/data/definitions/35.html) vulnerability in links. E.g. here I made a demo:
https://beta.metaculus.com/questions/20776/cannabis-removed-from-us-schedule-i-by-2025/#comment-191043
I don't think it's dangerous there, but just decide if you want to allow in general links like "../../../something/something".

![image](https://github.com/user-attachments/assets/c05e3bef-3290-4fb6-92f0-aa5c5df8acdc)

**Comment by hlbmtc** [comment]
This should not be the issue for nextjs/django routing
