### ISSUE TITLE
Election Hub graph size

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#671]
Just make the graph on the left taller:

![image](https://github.com/user-attachments/assets/25da1d1e-ac60-41cc-9b88-910b1b30d0f6)

Reported by @ryooan. Is there an easy way to also not have mousing away from the graph leave that residual x=[date] line there OR make it so that the line stays but the x axis labels aren't there, only [date] (which is how it works as you're mousing around...)? If it's not extremely easy I wouldn't worry about it.

**Comment by ncarazon** [comment]
@hickman-santini looks like this was already fixed?

Beta:
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/b5a43142-82e2-4019-888e-12b3f320287f">
