### ISSUE TITLE
API page

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#677]
API page currently 404s: https://dev.metaculus.com/api/

Instead, let's migrate this little flat page: https://www.metaculus.com/api-update-9-24/

And add this line after "Full documentation will be available in the next few weeks:"

_For reference on POST endpoints and other legacy features, you can still consult our previous API documentation at https://old.metaculus.com/api._

**Comment by hickman-santini** [comment]
For now (until we generate new API docs), beta.metaculus.com/api should redirect to this notebook (which will come over to the beta next time we do a db dump, right?) - https://www.metaculus.com/notebooks/28595/updates-to-metaculus-api/

**Comment by hickman-santini** [comment]
@ncarazon next time we do a db dump, can you make https://beta.metaculus.com/api redirect to https://beta.metaculus.com/notebooks/28595/updates-to-metaculus-api/

**Comment by SylvainChevalier** [comment]
lgtm
