### ISSUE TITLE
All Questions need to have `open_time`

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#692]
Currently the `open_time` field on the `Question` model is nullable. This can't be the case since open time is required for scoring.
It seems as though the question creation validation doesn't enforce setting an open_time (or inferring it from when the question is created or approved).

So we need to set the `open_time` field to not be nullable or blank, and then follow the consequences through question creation.
It looks like the `migrate_old_db` does a good job of populating the `open_time` field, so that's a major plus.

**Comment by hlbmtc** [comment]
Fixed. I saw no records with nullable open_time, so no extra actions required

**Comment by hlbmtc** [comment]
@lsabor We set `open_time` to the current dt upon approval, so the only questions with nullable values are not active

**Comment by SylvainChevalier** [comment]
Questions don't have open times before they're open, closing.
