### ISSUE TITLE
Ensure question dates timezones

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#699]
- Ensure FE passes Close & Resolution dates in UTC format, but datepicker works in user's local timezone. You can check `DatetimeUtc` component
<img width="875" alt="image" src="https://github.com/user-attachments/assets/3eeb587b-bf9e-445e-bd6f-a4da48e39824">
- Ensure we convert this dates to user's local TZ:
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/bf5129f1-419d-4dc2-ab55-58ce99c389b8">

**Comment by ncarazon** [comment]
Ready for testing on dev and prod
