### ISSUE TITLE
Notebooks should show up on main feed

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#707]
Notebooks should show up on main feed, not just news feed.

"I believe it's hotness based on prod, we typically boost and bury them in the same way as questions, and they naturally fade from the hot view over time as they lose rating." - @ryooan 

E.g. on www

![image](https://github.com/user-attachments/assets/a1b34608-5c4e-4d81-987d-21fe5a8ccc81)

**Comment by ncarazon** [comment]
@hlbmtc re-assigning to you as this is BE issue

**Comment by hickman-santini** [comment]
User can boost-boost-boost until it shows up toward the top of the main feed if they want. Maybe on the old site the hotness of notebooks was "boosted" to a certain extent by default. We can discuss this later! Downgrading to medium.
