### ISSUE TITLE
Improve question creation errors handling

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#709]
## Current behavior
Currently, frontend does not notify use about any BE errors happening during question/post creations. 

## Expected/desired behavior
- Add errors handling for unexpected events (e.g critical BE exception)
- Add buttons loading states (disabled)
- Add console.error logging

**Comment by SylvainChevalier** [comment]
Doesn't seem blocking for launch, am I missing something?

**Comment by SylvainChevalier** [comment]
Who should QA this? I'm assuming @hlbmtc ?

**Comment by ncarazon** [comment]
Ready for testing on dev and prod
