### ISSUE TITLE
Lime green histogram

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#713]
I thought we'd gotten rid of this color? Can we make sure it's not anywhere:

![image](https://github.com/user-attachments/assets/b8882e4f-b2a2-4d14-8f01-cd400309ec6e)

https://beta.metaculus.com/questions/111/total-solar-eclipse-in-2522/

**Comment by SylvainChevalier** [comment]
Duplicate of #492

**Comment by hickman-santini** [comment]
@ncarazon thanks for also fixing the black axis labels in dark mode - looks great - closing both issues
