### ISSUE TITLE
Resolution criteria truncated on old question

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#714]
This one: https://beta.metaculus.com/questions/111/total-solar-eclipse-in-2522/

See [www](https://www.metaculus.com/questions/111/will-there-be-a-total-solar-eclipse-on-june-25-2522/) for full resolution criteria.

On old questions there was no "background info." If background info is empty, don't show the toggle header at all.

![image](https://github.com/user-attachments/assets/f96d8160-8995-4973-9017-d18dce8336d9)

Spot-checking a few other old questions... Some are fine but These ones also have truncated resolution criteria or empty resolution criteria (there is text on www):

https://beta.metaculus.com/questions/109/
https://beta.metaculus.com/questions/190/
https://beta.metaculus.com/questions/199/

Reported by Bruno

**Comment by hlbmtc** [comment]
I made a small investigation, enabled errors logging and seems like it's our MDXEditor fails to compile some basic links references.
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/83a0fcd9-1607-412b-ab94-736e8f27834e">

So seems like our MDXEditor is very sensitive. 
This is a quick example of github markdown that does not work either -- https://gist.github.com/emedinaa/28ed71b450243aba48accd634679f805

@ncarazon Reassigning this to you

**Comment by SylvainChevalier** [comment]
If the migration is done correctly and it's only a matter of processing in the rewrite, then this is not blocking.

**Comment by SylvainChevalier** [comment]
Iirc the solution is to enable some plugin in our markdown processor.
