### ISSUE TITLE
If a question gets un-resolved, remove scores.

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#715]
![image](https://github.com/user-attachments/assets/370725b8-498e-4259-b9db-20d8a1f900dc)

@ryooan resolved [this](https://beta.metaculus.com/questions/20785/starship-booster-tower-catch-attempt-in-2024/) then unresolved it and the scores remain

**Comment by hickman-santini** [comment]
Downgrading to medium priority, not blocking just cuz it doesn't happen often

**Comment by SylvainChevalier** [comment]
Well it's happened now on the new site, so bumping up.

**Comment by lsabor** [comment]
Unresolved questions no longer have scores on them. Closing accordingly
