### ISSUE TITLE
Allow spaces (and commas?) in multi-choice question choices

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#716]
When making multi-choice question, can't add spaces in the "Choices" text box (although you can add them once the choices appear below; thus not blocking)

![image](https://github.com/user-attachments/assets/dbe530cc-c93a-4997-85b7-06a048806d80)

> Also I'm not sure on the whole comma separated entry, I think the way multiple choice input on prod works currently is pretty nice and I worry that there could be multiple choice answers that need to contain commas that cause issues for people or something like that

How it works on www:

https://github.com/user-attachments/assets/6e5da33d-4f41-46e9-a33a-0fc26b630ab1

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by hickman-santini** [comment]
@SylvainChevalier do you think we should make it so that you can put commas in multi-choice question choices. If we did that we'd need to implement choices entry more like what google forms does:

![image](https://github.com/user-attachments/assets/106580b3-115f-43be-9694-152b2a6ab1c0)

**Comment by SylvainChevalier** [comment]
I think your video of "How it works on www" is exactly what we need, no?

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
Django admin still has the options in a long string, so saving will break things.
![image](https://github.com/user-attachments/assets/ed6080f3-4e4d-441a-9708-d17831bbbe2b)
Example: ("option 1", "option, 2") will turn into ("option 1", "option", " 2")
(Tested [here](https://dev.metaculus.com/admin/questions/question/28230/change/?_to_field=id).)

**Comment by hlbmtc** [comment]
Adjusted admin panel

**Comment by SylvainChevalier** [comment]
lgtm
