### ISSUE TITLE
Can't resolve to value outside the bounds

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#723]
## Current behavior

Not permitted to resolve a numeric-range question to a value outside of the bounds even if bound(s) is/are open.
![image](https://github.com/user-attachments/assets/fff00e33-c83b-424b-ad0a-21121ca877c1)## Expected/desired behavior

## Expected behavior

If the left bound is open, should be allowed to resolve to a value < left bound. If the right bound is open, should be allowed to resolve to a value > right bound.

**Comment by SylvainChevalier** [comment]
Spec [here](https://www.notion.so/metaculus/Rewrite-resolutions-701a6f10a5154ff589a1e5eb9ff4b655).

**Comment by ncarazon** [comment]
@lsabor adding you a second assignee to do the BE part of supporting unknown resolution values as discussed on a call

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm
