### ISSUE TITLE
"Hot" sort doesn't work

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#729]
On dev right now:
![image](https://github.com/user-attachments/assets/8b2b2835-2990-4b5d-b169-2eadfa5e76ae)
"Will the Universe end?" has no recent comments or predictions, so it shouldn't be 4th.

Also boosting has no apparent effect. If that's a separate problem we'll make another issue.

**Comment by hickman-santini** [comment]
Boost/bury not appearing to work because we recalculate hotness every hour. Let's make it ten minutes.

Hotness "window" is 7 days, which probably explains hotness sort seeming weird.

**Comment by hlbmtc** [comment]
@SylvainChevalier Clanged hotness updation frequency to 10 mins + now your boost/bury actions will instantly update hotness for our feed
