### ISSUE TITLE
Custom embed themes

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#731]
Make a custom theme for embeds:

- Pilot for our friends at [Verity](https://www.verity.news/).
- Behind a url parameter, e.g. `theme=verity-light`, `theme=verity-dark`.
- Make minimal changes:
    - Serif font
    - Smaller title
    - Colours as the screenshots below ([source](https://www.verity.news/story/2024/fbi-violent-us-crime-dropped-sharply-in-early-))
    - <img src="https://github.com/user-attachments/assets/39a68cde-a5e7-4d62-8480-ccc61873c741" width=50%>
    - <img src="https://github.com/user-attachments/assets/77b3e565-6a26-4357-b294-f898ba6ee845" width=50%>

Then we point Verity at the new code and tell them we welcome a PR to make the style their own.
And next time someone asks for a custom embed style, we also point them at the code and our [Readme#Contributing](https://github.com/Metaculus/metaculus?tab=readme-ov-file#contributing).

**Comment by ncarazon** [comment]
Making this high priority due to request by Verity team

**Comment by ncarazon** [comment]
Ready for testing on dev and prod

**Comment by SylvainChevalier** [comment]
how do I use the themes? https://www.metaculus.com/questions/embed/1088/?theme=verity-dark does not seem to work

**Comment by ncarazon** [comment]
we can use `embed_theme` parameter to pass a custom theme, just `theme` is used to set our dark/light theme
https://www.metaculus.com/questions/embed/1088/?theme=light&embed_theme=verity-dark

**Comment by SylvainChevalier** [comment]
looks broken: https://www.metaculus.com/questions/embed/1088/?theme=dark&embed_theme=verity-dark
![image](https://github.com/user-attachments/assets/699595c8-3f55-4e33-a1cd-783c09923e56)

**Comment by SylvainChevalier** [comment]
Also the graphs are not currently broken on Verity, so bumping to medium.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm!
