### ISSUE TITLE
Don't show "Forecast data is empty" on upcoming questions

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#738]
Questions that are upcoming should have a message that you can't predict yet because it's still upcoming (below) AND don't show "Forecast data is empty"

Current:

![image](https://github.com/user-attachments/assets/09d13c53-6716-4346-a613-b9e1ff9cb4bd)

Expect behavior:

![image](https://github.com/user-attachments/assets/9ade6532-26de-4859-8e35-1859fb10ae76)

**Comment by SylvainChevalier** [comment]
Also in feed tiles.
![image](https://github.com/user-attachments/assets/88f3f7f2-458b-45b3-bd5e-edc1cd189818)

**Comment by ncarazon** [comment]
Ready for testing on dev and prod

**Comment by SylvainChevalier** [comment]
lgtm.
