### ISSUE TITLE
Style the bulletins

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#751]
The bulletins are ugly
![image](https://github.com/user-attachments/assets/fc37cc8c-1021-4781-9e15-ac139dac7f44)

@ncarazon can you make them not ugly, or do you need assistance from @aseckin?

**Comment by hickman-santini** [comment]
![image](https://github.com/user-attachments/assets/ef304940-b966-4627-bd6c-e2ad34571218)

We made a new issue for [html](https://github.com/Metaculus/metaculus/issues/763). Closing this
