### ISSUE TITLE
Need button to show bot comments (hidden by default)

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#753]
## Current behavior
You can't see bot comments even if you want to.

## Expected/desired behavior
Add button to show bot comments (doesn't need to say # of comments if that's not trivial):
![image](https://github.com/user-attachments/assets/d144f356-2fc6-4e13-b91e-e806b8b3662c)

**Comment by ncarazon** [comment]
@hlbmtc looks like we currently don't support this filtering on BE. Could you, please, add it to the endpoint? I assume we'll also need some flag on the post level to check if this filter should be available on FE.

@hickman-santini could you, please, give an example of question, that supports this filter on prod?

**Comment by hickman-santini** [comment]
@ncarazon ah, sorry, it's only on AI Benchmark questions like (which is how
it should be):
https://www.metaculus.com/questions/26840/will-tesla-increase-its-production-in-q3-2024-compared-with-q2-2024-/

**Comment by SylvainChevalier** [comment]
Should we close this?

**Comment by hickman-santini** [comment]
> Should we close this?

We made it so that bot comments are all visible, partial fix. I think we should still make them hidden by default and add the "show" button, since bot comments are so dang long and someone might want to quickly just see real people's comments? I'm not wedded to this though, @SylvainChevalier defer to you.

**Comment by SylvainChevalier** [comment]
Let's wait for several users to ask for this, as a signal that it's actually valuable.

**Comment by lsabor** [comment]
More users have requested this now that some bots are out in the wild, so I think it should not be closed.

**Comment by SylvainChevalier** [comment]
Agree something needs done.

Hiding but comments by default works poorly because we'll soon want to use a bot for Key Factors.

Solution: collapse bot comments by default until they have +3 net score.

**Comment by SylvainChevalier** [comment]
Closing this and opening a new one for clarity.
