### ISSUE TITLE
If user has "hide CP" setting on, also hide the histogram on question page

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#756]
## Current behavior
Histogram kind of defeats the purpose of hiding the CP, although you have to scroll down to see it on most screens so I'm not fussed.
![image](https://github.com/user-attachments/assets/9eb85603-0ece-45a1-b0ce-8c7ae0bcb238)

## Expected/desired behavior
Do the same thing as with the CP over time graph. If they click "Reveal temporarily" in either place, reveal both the CP graph and the histogram.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by hickman-santini** [comment]
Thanks! LGTM
