### ISSUE TITLE
On binary group questions, sliders show CP when CP is hidden

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#757]
## Current behavior
![image](https://github.com/user-attachments/assets/abc7c4c5-4eef-44af-a2e9-f49e2ce79af1)
and if one of the groups has resolved it shows the CP graph even if you have "CP hidden" in your settings:
![image](https://github.com/user-attachments/assets/15ea853e-1fea-423b-90a9-0180fab20301)

## Expected/desired behavior
- If I've hidden the CP, don't show me the CP arrows under "Make a prediction"
- Whether a group is resolved or not should determine whether the arrow _for that group_ is shown AND whether the CP line _for that group_ is shown (one group resolving shouldn't trigger CP for all groups to be revealed)

**Comment by SylvainChevalier** [comment]
@hickman-santini could you consolidate all the "hide the CP from me" issues into one? I see #835 and #602 at least.

**Comment by SylvainChevalier** [comment]
@hickman-santini could you consolidate all the "hide the CP from me" issues into one? I see #835, #602 and #756 at least.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
