### ISSUE TITLE
Fix the tournament page question filters

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#781]
Should not have all this stuff:
![image](https://github.com/user-attachments/assets/5e2326b0-7660-4926-b70f-f89614116a8d)
@SylvainChevalier to write down what it should have.

**Comment by SylvainChevalier** [comment]
Should have:

- Question type
  - Numeric, Date, ...
- Question status
  - Draft, In Review, Open, Upcoming, Closed, Resolved, Deleted
- Question Author
- My Participation
  - Predicted
  - Not Predicted

**Comment by ncarazon** [comment]
@SylvainChevalier this seems to be fixed on prod, but Question status has fewer options. Is this expected?

<img width="509" alt="image" src="https://github.com/user-attachments/assets/141c0230-996d-487a-b1c0-cddd6a689de1">

**Comment by SylvainChevalier** [comment]
Not expected, it'd be better to have all the statuses there.

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm!
