### ISSUE TITLE
Homepage "See More posts" should lead to News>Research

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#783]
The link on the bottom right here links to https://metaculus.medium.com/
![image](https://github.com/user-attachments/assets/302aef58-1cd4-4803-91f4-c57a3d6d3928)
It should link to https://beta.metaculus.com/news/?news_type=research instead.

**Comment by lsabor** [comment]
completed by @EloiseRosen 
Closing
