### ISSUE TITLE
Reminders update frontend changes

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#796]
## Current behavior
Now our backend supports multiple datetime reminders, so we need to update frontend to change the way it handles subscription changes:
- Initially, we were relying on `type`. It was the indicator of whether subscription type needs to be created or updated.
- Now we rely on subscription id

TODO:
1. Update subscription to pass `subscription.id` of the existing subscription if modifying it. If creating a new one -- don't pass id at all.
2. Make `PostSubscriptionType.SPECIFIC_TIME` subscriptions support multiple entries, so we could add/remove/render N reminders of this type. Other types should stay single as before
3. Push it to https://github.com/Metaculus/metaculus/pull/795 where all related BE changes are located

Related ticket with mocks -- https://github.com/Metaculus/metaculus/issues/785

**Comment by SylvainChevalier** [comment]
lgtm
