### ISSUE TITLE
For logarithmic date range question, zero point should be a date

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#798]
_Low priority because... have we ever wanted to make a date range question logarithmic? Maybe we should rather just remove "Is Logarithmic" option from date range questions? I can imagine cases where you'd want this but idk if we need it._

## Current behavior
If you select "is logarithmic" when making a date range question, the zero point is still a decimal (defaults to 2.8):
![image](https://github.com/user-attachments/assets/b7067ced-f147-4761-b1a9-bf0a0c466249)

## Expected/desired behavior
Zero point input should be a date

**Comment by SylvainChevalier** [comment]
Ftr we do want / have log-scale date questions.

**Comment by lsabor** [comment]
done
