### ISSUE TITLE
some comments can crash the markdown parser

### ISSUE THREAD

**Issue by draaglom** [Metaculus/metaculus#819]
## Current behavior

comments ported from old.metaculus.com including a left angle bracket followed by any character are broken:

[e.g.](https://www.metaculus.com/questions/20789/#comment-195138) my comment here

It contains the string `<4%` which appears to crash the markdown engine

Note that if you enter a < in WYSIWYG mode, it's fine because it auto escapes it as `\<`; only a < which got ported from the old app (or entered directly via the raw input mode) triggers this issue.

## Expected/desired behavior

All comments on old.metaculus.com should be visible on the new site

**Comment by SylvainChevalier** [comment]
I'll add that writing a "<" in markdown mode also crashes the wysiwyg editor, with a rather cryptic message.
![image](https://github.com/user-attachments/assets/0907cbf8-5519-4ccf-8e5a-4b59f5fea038)
We should either improve the error message, or escape the "<" even in markdown, or not crash on it.

**Comment by ncarazon** [comment]
Ready for testing on dev and prod

**Comment by SylvainChevalier** [comment]
lgtm
