### ISSUE TITLE
Pending and non-news notebooks shouldn't appear in news

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#830]
Spam accounts are making discussion notebooks like these and they're appearing in news. *_**No discussion**_* notebooks should appear in news.

![image](https://github.com/user-attachments/assets/2bf4b185-f021-40c1-b5bd-3646434b004e)

**Comment by ncarazon** [comment]
> On the news page, only show notebooks that are in a "news category" type project

Done

> Only show pending notebooks to mods and admins

This should be done on BE side as we fetch the data with pagination. @hlbmtc could you please handle that? Assigning you to this ticket.

**Comment by lsabor** [comment]
I'm not sure what's left. Are there still pending notebooks displayed to non staff?

**Comment by lsabor** [comment]
Spam in news is fixed.

Minor improvements still: don't filter news feed for only notebooks of type news

Unsure about status of pending notebooks in feed, so unless it is seen again it might not be worth investigating.

Thus moving down to Low Priority.
