### ISSUE TITLE
handle "<" more gracefully in markdown editor

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#842]
yes, the new markdown processor needs "<" to be escaped. only happens for migrated content, since the new ui escapes them automatically.
we should:
• fix all the known instances
• improve the error handling

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1728402658609969?thread_ts=1728399662.613139&cid=C01Q9AQBVHB)

**Comment by PatMyron** [comment]
Jinx again:
https://github.com/Metaculus/metaculus/issues/819
https://github.com/Metaculus/metaculus/issues/820

**Comment by SylvainChevalier** [comment]
Duplicate of #818
