### ISSUE TITLE
Scrolling the feed is difficult on mobile

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#848]
While scrolling the feed on mobile, if my finger happens to land on a graph, it doesn't scroll.

**Comment by hlbmtc** [comment]
I also noticed this. Seems like when your fingers touch chat area, it does not affect global scroll, but start interacting with chart

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm!
