### ISSUE TITLE
Hover state doesn't always correspond to graph

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#857]
https://www.metaculus.com/questions/21553/ai-causes-1k-deaths-or-200b-loss/

![image](https://github.com/user-attachments/assets/8fb886dd-ea2b-4fec-a8e2-e55d52e3c3f6)

**Comment by ncarazon** [comment]
Ready for testing on dev and prod

**Comment by SylvainChevalier** [comment]
lgtm
