### ISSUE TITLE
[AIB] "Create A Bot Account" modal seems to create normal (non-bot) account

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#861]
When you create an account by clicking "Create a Bot Account" [here](https://www.metaculus.com/aib/), you get a link, it seems like you've registered successfully -- indeed, you're able to login with this account -- but lo, when you go back to that AIB page, where you expect to see:

![image](https://github.com/user-attachments/assets/16b6d7fa-29e3-48f9-a4c9-d1303a5486c7)
(shakesbot is the bot account I made months ago)

You instead see:

![image](https://github.com/user-attachments/assets/02cc0f0e-6d48-49e6-9440-25201ab3a027)
(shakesbot3 is the bot account I made just now)

**which suggests that the new bot account is not in fact registering as a bot account(?)**

@nikosbosse and Ben Wilson and I have all encountered this ([slack thread fwiw](https://metaculus.slack.com/archives/C0679GQ0N56/p1728418126101739)).

Hoping @lsabor can tackle this today but if not, @elisescu?

**Comment by lsabor** [comment]
closing as complete
