### ISSUE TITLE
Fallback to raw markdown if encountered errors during rendering

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#864]
## Current behavior
<img width="836" alt="image" src="https://github.com/user-attachments/assets/847f3b98-d9c8-49d0-b44b-3f4b40d1f9ef">
We have a lot of broken markdowns, so the tmp solution could be rendering raw content in case of critical error. 

[Example](https://www.metaculus.com/questions/11245/2024-us-presidential-election-winner/#comment-195424)

Please ensure we don't render html tags taken from raw content to prevent potential security issues

**Comment by SylvainChevalier** [comment]
Related to #819

**Comment by ncarazon** [comment]
Ready for testing on dev and prod

**Comment by SylvainChevalier** [comment]
lgtm
