### ISSUE TITLE
Can no longer filter questions using `not_guessed_by`

### ISSUE THREAD

**Issue by pgodzin** [Metaculus/metaculus#876]
## Current behavior
Describe the current behavior of the thing you wish to change. Please provide relevant links and screenshots

`not_guessed_by` query param to /questions/ API is not respected

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

Questions are filtered by those not yet guessed by the given user

**Comment by SylvainChevalier** [comment]
I believe this was replaced by `not_forecaster_id=`. @hlbmtc could you confirm?

**Comment by elisescu** [comment]
Working on a fix to enable the `not_guessed_by` so the API is backwards compatible with respect to that param too.

**Comment by pgodzin** [comment]
from what I can tell the PR has been merged and deployed, but still not seeing the filtering applied:

https://www.metaculus.com/api2/questions/?limit=20&offset=0&project=32506&status=open&not_guessed_by=191935

**Comment by elisescu** [comment]
You are right, @pgodzin. We do seem to have some issues with that filter, my bad. 
We are looking into it.

**Comment by lsabor** [comment]
@pgodzin Try it now.
If it works, feel free to close this ticket.

**Comment by pgodzin** [comment]
works, thanks!
