### ISSUE TITLE
Ambiguous and annulled look like yes resolutions

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#877]
The dot shouldn't show on the chart, makes it look like it resolved yes.

 ![Screenshot_20241009-085401.png](https://github.com/user-attachments/assets/84624e75-f6a5-4685-b7c1-c52dc85bfe4e)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
