### ISSUE TITLE
`add_posts_to_main_feed` missing from django admin

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#881]
It should be possible to edit the `add_posts_to_main_feed` option when editing a project in the Django admin.
It would also be nice if it was one of the filters in the project list as well.

**Comment by SylvainChevalier** [comment]
Todo @SylvainChevalier: check that recent projects have the option set correctly.

**Comment by hlbmtc** [comment]
After a brief discussion last week: we have this option on tournament level available for site admins:
<img width="812" alt="image" src="https://github.com/user-attachments/assets/08579ad5-d91c-46a1-bd79-7dd51c88064d">
