### ISSUE TITLE
Comment Insight optimization

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#882]
https://github.com/Metaculus/metaculus/commit/2cf15af7f8fc9cfec184e32dd6de352c80b929a1

This PR reverts a change to comment insight calculation due to an error. The reverted code is much slower so a second attempt to optimize is necessary.

**Comment by hlbmtc** [comment]
Optimized here -- https://github.com/Metaculus/metaculus/commit/9a701ec6c17b868dcc41c956b9ebc2daa5d0c131
