### ISSUE TITLE
Allow reaffirming predictions

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#892]
When a forecaster gets to a question they have forecasted before, and before they've moved any of the slider, the predict button should not be disabled but say "Reaffirm" instead.
Applies to all question types.
![image](https://github.com/user-attachments/assets/cf97c2f1-6611-4363-abec-27711a407a6e)

**Comment by ncarazon** [comment]
Ready for testing on prod

**Comment by SylvainChevalier** [comment]
lgtm
