### ISSUE TITLE
Continuous conditionals show the wrong forecast

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#894]
The "my prediction" under "If yes" and "If no" of a conditional shows the wrong forecast for continuous questions. See this one for example: https://www.metaculus.com/questions/28527/us-annual-co2-emissions-with-land-use-change-2028/

![image](https://github.com/user-attachments/assets/bab97721-58f1-4264-8d7b-a89083ef8982)

## Expected behavior
"My prediction" should be the median.

**Comment by SylvainChevalier** [comment]
@ncarazon still broken for me, [on the same question](https://www.metaculus.com/questions/28527/us-annual-co2-emissions-with-land-use-change-2028/):

The number on the "if no" line is 6.37, my median in the table below the graph is 5.56B. They should both be 5.56B.

![image](https://github.com/user-attachments/assets/e0e6aeb4-5ba1-401b-9653-10091c7e949d)

**Comment by ncarazon** [comment]
@SylvainChevalier The fix has been deployed to the development environment but is not yet in production. Should I add the ‘Awaiting QA’ label only after the deployment to production?

**Comment by SylvainChevalier** [comment]
> Should I add the ‘Awaiting QA’ label only after the deployment to production?

No, though we are in the awkward situation that, for now, we often push things directly to prod, so it's unclear which environment to test. For the time being, could you write in a comment where it is that you push changes for QA?

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm
