### ISSUE TITLE
Comments in threads should be in chronological order

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#896]
It looks like comments from before the switch are in reverse chronological order, but comments from after the switch are in chronological order.
Compare [here](https://www.metaculus.com/questions/11245/2024-us-presidential-election-winner/#comment-195209):
![image](https://github.com/user-attachments/assets/4f5bd914-eaf3-480e-8c12-2fc271dc0b5a)
And [here](https://www.metaculus.com/notebooks/28734/#comment-195444):
![image](https://github.com/user-attachments/assets/14ce89a4-6a6e-4bd9-95e4-0059da2fe10e)

**Comment by nangchrys** [comment]
At least some new comments are in reverse chronological order too.

![image](https://github.com/user-attachments/assets/b55c7db7-7ed5-424f-a0cd-258b039313fa)

**Comment by ncarazon** [comment]
@SylvainChevalier I've reviewed links provided in the ticket, as well as several other questions/notebooks. It seems that the issue has already been resolved, or there may have been some misunderstanding based on the initial comment. Currently, when we copy the link to a specific comment, it moves that comment to the top of the comment section to ensure easy navigation. So this order mismatch is expected.

**Comment by SylvainChevalier** [comment]
discussed in sync:
- top level comments should be sorted according to the drop down menu
- replies in a given thread should always be sorted from oldest to newest.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm.
