### ISSUE TITLE
Show more digits for extreme probabilities

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#898]
Whenever we show probabilities <3% or >97%, we should show one more digit, e.g. 1.7% or 99.8%.
Please make this apply to everywhere we show probabilities, including the CP values, on feed tiles, for mass out of continuous bounds, etc.

**Comment by nangchrys** [comment]
Duplicate of [#539](https://github.com/Metaculus/metaculus/issues/539)? As I said there too, I think it's better if this is the case for all predictions.

**Comment by SylvainChevalier** [comment]
Duplicate of #539 
Let's take it there.
