### ISSUE TITLE
reinstate the random question button

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#911]
In the old site there was a dice button in the top right of a question page which sent you to a random open question.

**Comment by SylvainChevalier** [comment]
This may have been one of the most internally divisive features of the old site =]. I happen to think it's fun, but to keep it reasonable:
- It should only be visible in the feed when "feed home" is selected.
- It returns a question from the `Site_main: Metaculus Community` project.
- It can also be on question pages, next to the share button.

**Comment by lsabor** [comment]
I don't recall any internal divisiveness, but do remember positive sentiment. It was definitely discussed and dismissed during rewrite prioritization, and I think maybe someone who is no longer at the company might have objected to it. But I think everyone left is pretty enthusiastic about it.

This PR: #1605 adds it back, and puts it right next to the global search in the header. I made it return a random open & approved question that the user has access to. Let me know if that will be ok or if I have to respect the spec.
