### ISSUE TITLE
Question pages scores are missing CP scores and are not styled

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#918]
Then:
![image](https://github.com/user-attachments/assets/df09200e-164d-40f9-b9a1-642b3dcad842)

Now:
![image](https://github.com/user-attachments/assets/1453660e-80e0-4f8b-9f4c-7206104f19fd)

**Comment by lsabor** [comment]
Found and squashed the bug preventing CP scores from displaying.
@ncarazon handing it off to you for styling - `score_display.tsx` is the file

Moving to medium priority since it's only a styling issue left.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by lsabor** [comment]
Great that's just what it needed to be!

**Comment by lsabor** [comment]
closing as complete, thanks @ncarazon
