### ISSUE TITLE
Predictions attached to comments weren't migrated

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#919]
It's possible to attach predictions to comments, like this:
![image](https://github.com/user-attachments/assets/c1492628-59d9-4724-b2fd-677a52abda9a)
The data is stored in `latest_prediction` of `metac_question_comment` of the old database.
I understand it's not in the same format, but that's no reason to not import them.
[Here](https://data.heroku.com/dataclips/msnqdxrkzqqqremagxnlznacjdxn)'s a dataclip that gives you the data in the new format.

**Comment by hlbmtc** [comment]
@SylvainChevalier Migrated, please confirm

**Comment by hlbmtc** [comment]
@SylvainChevalier Migrated, please confirm
