### ISSUE TITLE
Fix top of comment feed ui

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#924]
The hierarchy feels quite confusing to me here:
![image](https://github.com/user-attachments/assets/fbc12aba-8dc7-4422-b44d-66e7c5f49af5)

I propose at the very least this:
![image](https://github.com/user-attachments/assets/ba188cb3-d20d-4b46-a741-b4418ffa4c5d)

Changes:
- shortened copy of checkboxes and moved them together
- moved "new comment" box above feed, gave it its own smaller header
- added some copy and opacity to the comment counters and sort line, and removed spacing
- renamed "Recent" to "newest" (not capitalised).

@aseckin if you have more suggestions they are very welcome, but I think this is a good start. (We could e.g. drop the "Comments" header, I think it's pretty clear what that section is.)

**Comment by aseckin** [comment]
Fixed as part of https://github.com/Metaculus/metaculus/pull/1232
