### ISSUE TITLE
deleting a component changes the location of other component weight sliders

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#926]
essentially it appears as while the first component was deleted, the last weight slider was deleted with it
before:
![image](https://github.com/user-attachments/assets/4af70778-a641-45cc-ad82-12cc92e6fa3b)
after:
![image](https://github.com/user-attachments/assets/9c617d1f-a49e-480a-ba07-17abccee97b5)

but this is only appearance, the actual weight of the components in the predictions doesn't change unless you touch the sliders

**Comment by SylvainChevalier** [comment]
Tbc: it looks like he deleted the _first_ component, and:
- The _first_ position slider was deleted
- The _last_ position slider was deleted (this is the error)

**Comment by nangchrys** [comment]
Do you mean the last weight slider?

**Comment by SylvainChevalier** [comment]
lgtm!
