### ISSUE TITLE
Show their predictions to users who hide the CP

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#937]
## Current behavior
When the CP is hidden, either because of user settings or because of the hidden period at the beginning of the question, my own forecasts don't appear anywhere besides the prediction interface.
Feed:
![Screenshot 2024-10-10 at 18-32-50 Metaculus](https://github.com/user-attachments/assets/27a49c32-66f3-4c56-bdc0-464ca045ff9f)
Question page:
![Screenshot 2024-10-10 at 18-30-17 Will there be Human-machine intelligence parity before 2040](https://github.com/user-attachments/assets/3763d37b-5582-417d-aacc-3e62ae646588)

## Expected/desired behavior
I would prefer if my current forecasts were visible from the feed, so that I can easily 1) know which questions I've forecasted on, 2) see what my forecasts are and if I no longer agree with them, without needing to open one tab per question.
![Screenshot 2024-10-10 at 18-37-16 Question Feed](https://github.com/user-attachments/assets/1c18e715-a01b-46d7-b87a-284be9af3eab)
I don't care about the number of the forecasters at all or the date that much and divergence shouldn't be showing anyway given that the CP is hidden. I only want the number 86% to appear anywhere in this box.

I would also like to see my past forecasts on the question page so that I know how I ended up where I am, when was the last time I updated, and by how much, without needing to either reveal the community prediction or wait for it to be revealed. Both the dots and the number below are essential.
![Screenshot 2024-10-10 at 18-37-37 Bitcoin up over 2024 Metaculus](https://github.com/user-attachments/assets/14f15deb-12df-4d02-b546-ba38c1be65cc)

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by nangchrys** [comment]
Thank you for implementing this! A few comments:
It would be nice if I could see the numbers of my predictions when mouseovering the graph in multiple choice and group questions, which I'm not able to do right now:
![image](https://github.com/user-attachments/assets/ba06f9e9-90b9-4c0e-8874-4463060764c9)

For group and multiple choice questions I should be seeing the numbers of my predictions, besides the graph, from the main feed:
![image](https://github.com/user-attachments/assets/d0b21837-e843-4529-bd3a-fa61c3f5670f)

The CP being hidden from all should function basically the same as me turning it off from my settings (besides the "reveal temporarily" button ofc). Right now, when the CP is hidden I see what I was seeing before:

- No graph when I open the question or in the main feed
- No way to tell I've predicted on the question from my main feed

Very minor, but when I haven't predicted on a question and I have the CP hidden I'm shown an empty graph in the main feed:
![image](https://github.com/user-attachments/assets/8a78d36e-9ff4-436e-8555-f1e918e03066)
It'd probably be nicer if I wasn't.

**Comment by leonardthethird** [comment]
Is this the right place to add that we should remove "Forecast data empty" from question tiles on feeds?
<img width="592" alt="image" src="https://github.com/user-attachments/assets/83e4cd75-e5b6-4b19-aadc-f74680c82d6e">

**Comment by ryooan** [comment]
Looks like that was fixed for upcoming questions but not hidden questions, agree that should be fixed! Either with a nicer message about the hidden period or showing nothing there. https://github.com/Metaculus/metaculus/issues/738

**Comment by nangchrys** [comment]
There are two more things that could be improved when the user has hidden the CP:
- Mouseovering the graph should show the user's forecasts (I mean the actual numbers)
![379259601-ba06f9e9-90b9-4c0e-8874-4463060764c9](https://github.com/user-attachments/assets/d279daf8-90de-45d9-9563-ba4fcf073b38)

- All questions should show the user prediction from the main feed, right now group and multiple choice questions don't
![379260670-d0b21837-e843-4529-bd3a-fa61c3f5670f](https://github.com/user-attachments/assets/58b45f05-918b-4608-9b25-87cec0a35237)

**Comment by SylvainChevalier** [comment]
The second bullet point is indeed more of a design question, and I leave it to @aseckin: do we show the number of forecasters and user predictions in the feed tile for groups and multiple choice questions, and if so where. My two cents is that it would be nice, but not worth making the tiles too ugly.

The first bullet point is simpler: when the user hides the CP, and they hover over the timeline on the question page, they should see the popup with their predictions, but the CP blanked, like in the table below.
|current|desired|
|-|-|
|![image](https://github.com/user-attachments/assets/5b86e9f5-81a4-480f-ba29-3d46ddc7e810) | ![image](https://github.com/user-attachments/assets/51d76a54-f1c5-4842-838c-0443b8fc6b95) |

**Comment by SylvainChevalier** [comment]
The popup works!

But, I noticed the timeline is still hidden on groups that have a fan graph, and on conditionals. Example group [here](https://www.metaculus.com/questions/11609/self-driving-car-availability-by-sae-level/) and conditional [here](https://www.metaculus.com/questions/15162/us-climate-emissions-halved-by-2030/) for me (105951):

![image](https://github.com/user-attachments/assets/aacc22c3-53ab-415a-b12c-a75fc279dd18)

**Comment by ncarazon** [comment]
@SylvainChevalier pushed a fix to dev

**Comment by hickman-santini** [comment]
LGTM! Timelines showing for fan graphs and conditionals with my forecasts. Looks like it's already on prod.
