### ISSUE TITLE
Binary community prediction chips and question detail pages are all showing 0%

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#946]
Binary community prediction chips and question detail pages are all showing 0%

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1728593064457319)

![image](https://github.com/user-attachments/assets/5d321cfa-ffc9-4cfe-a8c2-5bd2bd501b3d)
(While you're at it @ncarazon the number next to the person icon shouldn't be a % - can you remove the % (and make sure it's number of forecasters who have made forecasts on the question))

![image](https://github.com/user-attachments/assets/3e0e2506-4603-4b17-8ee7-b1dca0cea69e)

**Comment by lsabor** [comment]
closing as complete - currently merging and deploying.
