### ISSUE TITLE
Overlapping / broken question creation boxes

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#947]
User reports that on Safari question creation boxes overlap: https://www.metaculus.com/notebooks/28734/#comment-195952

![image](https://github.com/user-attachments/assets/3069439d-4453-4dd4-974f-6345631a5bd4)

**Comment by hickman-santini** [comment]
I'm making this medium priority for the moment... Presumably they can use another browser in the meantime.

**Comment by ncarazon** [comment]
TODO: add Awaiting QA label once dev deploys are enabled again

**Comment by ncarazon** [comment]
Note: the issue only reproduces on older WebKit versions and works perfectly fine in the latest Safari. I was able to reproduce on iPad simulator with IOS 15.5

**Comment by ncarazon** [comment]
Ready for testing on prod
