### ISSUE TITLE
Stale filter mismatch 

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#948]
## Current behavior
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/e1ed78f6-a95f-490a-808c-82d2eae24160">
Stale filter uses `hotness` instead of `divergence`

**Comment by SylvainChevalier** [comment]
"Stale" is neither, it's last prediction time (ascending).

**Comment by SylvainChevalier** [comment]
Looks like you removed the "open" filter. It's necessary, otherwise I get a long list of old resolved questions.
