### ISSUE TITLE
:statue_of_liberty: :ballot_box: Need to round the pp differences on election stakes

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#954]
## Current behavior
Too many decimal places:
![image](https://github.com/user-attachments/assets/fae56f79-2a50-4218-b8ac-95b7fe76d382)

## Expected/desired behavior
Round all of these pp differences to the nearest tenth of a percentage point.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm
