### ISSUE TITLE
Resume GA4 analytics recording - add code snippet

### ISSUE THREAD

**Issue by christianMet2** [Metaculus/metaculus#956]
For GA4 analytics data recording to resume, the below code must be placed on every page after the <head> element.
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z09LZD0ZV0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z09LZD0ZV0');
</script>
```

**Comment by ncarazon** [comment]
Ready for testing on dev. 
Note, that I wasn't able to test locally, as I don't have access to Google Analytics

**Comment by christianMet2** [comment]
Data's appearing in our GA4 instance. Looks like it's working perfectly.
