### ISSUE TITLE
Embeds styling issues

### ISSUE THREAD

**Issue by ncarazon** [Metaculus/metaculus#964]
Armin from ITN mentioned some problems with embed styling:

> Sample: https://www.improvemynews.com/php/metaculus.php -> you can see the Y-axis numbers going out of the chart

> The vertical scroll is also added even though the iframe is set to 100% height and overflow to hidden.

> On some types of charts if no max height is defined, the metaculus logo and the height goes way out of bounds I don’t recall this being the case in the past.

**Comment by ncarazon** [comment]
@SylvainChevalier can you confirm this is a High Priority ticket?

**Comment by SylvainChevalier** [comment]
confirmed.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by ncarazon** [comment]
UPD: ready for testing on prod as well

**Comment by SylvainChevalier** [comment]
lgtm
