### ISSUE TITLE
Bring back filter by upvoted

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#966]
Multiple users have expressed that filter by upvoted was crucial for how they use the site. Example: https://www.metaculus.com/notebooks/28734/#comment-199652

**Comment by SylvainChevalier** [comment]
Thanks. Filtering by upvote was always kind of a hack. I'd rather introduce filtering questions you follow. It wouldn't be backwards compatible, unfortunately.

**Comment by ryooan** [comment]
Is there a downside to having it? Given people have relied on it and built the way they interact with the site around it, seems like it wouldn't add much complexity and would be valuable for some users.

**Comment by SylvainChevalier** [comment]
Well, downside is compexity-death-by-a-thousand-cuts. But yeah, I'm making the call to have it anyway. See #893.
