### ISSUE TITLE
can't edit the bounds of continuous questions

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#983]
The button gets pressed normally, but the result is a combination of my edit and old values, plus some stubborn open/closed axes settings. My attempt:
![image](https://github.com/user-attachments/assets/c117eaae-9e8b-439a-85dc-4f5557cf368a)

The result:
![image](https://github.com/user-attachments/assets/036b9021-989e-48ae-9bec-e51ca8385320)
1932 was there from question creation.

**Comment by ncarazon** [comment]
@lsabor It looks like a BE bug. The data sent for the update is correct, but the returned scaling value remains unchanged from its value at creation
![image](https://github.com/user-attachments/assets/4fd6631b-fe58-4744-916d-85bcb64c35d2)
![image](https://github.com/user-attachments/assets/9e7b5b11-f30d-4af8-824a-5ef9c3e75d3c)

**Comment by lsabor** [comment]
I think this is now addressed (to be deployed with next deployment). Moving to QA

**Comment by ryooan** [comment]
I think this may be related, but just tried editing the bounds on a draft question and the question saved but the edits didn't seem to work. Tried to make it so the bounds were open upper and closed lower, and after saving and going back into editing it showed open lower and closed upper, the reverse.

**Comment by nangchrys** [comment]
Put the reverse and you'll get what you want

**Comment by ncarazon** [comment]
I believe the same issue is mentioned [here](https://github.com/Metaculus/metaculus/issues/951), will close this one
