### ISSUE TITLE
Editing an open question might reset the project

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#984]
Seems like there might be a bug where editing an open question resets the project to just Metaculus community. <https://metaculus.slack.com/archives/C04H7L9UZ5G/p1728668020195969?thread_ts=1728666932.066089&amp;cid=C04H7L9UZ5G|https://metaculus.slack.com/archives/C04H7L9UZ5G/p1728668020195969?thread_ts=1728666932.066089&amp;cid=C04H7L9UZ5G>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1728668067568879)

**Comment by SylvainChevalier** [comment]
@ryooan I can't reproduce that, could you try again?

**Comment by ryooan** [comment]
@SylvainChevalier just tried it as well and couldn't reproduce it, might have been fixed
