### ISSUE TITLE
Show number of forecasters when displaying a single group subquestion

### ISSUE THREAD

**Issue by leonardthethird** [Metaculus/metaculus#987]
## Current behavior
As stated in title

## Expected/desired behavior
Users should be able to see the number of forecasters on each question in the group.  Pre-rewrite, this was done by hovering on the checkbox for the respective question, below the graph.  This was never ideal (as it's really nonobvious that the functionality exists unless you're random-walking your mouse around the screen), but I don't immediately have a better idea.

**Comment by SylvainChevalier** [comment]
To clarify:
- when a single subquestion is highlighted in the group combined timeline, show the number of forecasters
- this happens both:
  - when hovering over one of the checkboxes.
  - when a single subquestion is checked. In that case the number tracks the number of forecasters at the time the user is hovering over.

Screenshots from the old site:
![image](https://github.com/user-attachments/assets/35ff1664-c977-49c4-b725-85e96e5a0924)
![image](https://github.com/user-attachments/assets/8937b752-c8a6-4067-a06c-25862c79af45)

**Comment by ryooan** [comment]
Adding that number of forecasters would change as you pan across different time periods while hovering.

Additionally, you should be able to see number of forecasters on conditionals, but currently seems like there's no way to select only one branch of a conditional so additional though might be needed there, see this one for example: https://www.metaculus.com/questions/28503/chinese-invasion-of-taiwan-2030/

Also applies to multiple choice, for example: https://www.metaculus.com/questions/22795/president-of-croatia-in-2024-2025-election/

**Comment by lsabor** [comment]
@ncarazon These changes seem more up your alley than mine. Can you implement them?

**Comment by ncarazon** [comment]
Ready for testing on prod
