### ISSUE TITLE
Wrong y axis in combined continuous group timeline

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#989]
[At least on this question](https://www.metaculus.com/questions/13099/how-many-successful-orbital-rocket-launches-will-there-be-in-the-following-years/), the community prediction on the timeline is showing percentages when it should be a numeric range.

I have also seen it happen in the main forecast timeline, like in [this question](https://www.metaculus.com/questions/28269/?sub-question=28310)

**Comment by nangchrys** [comment]
I see normal numbers:
![image](https://github.com/user-attachments/assets/8b89275f-35b2-4757-b73c-eaf630774e13)

Could you post a screenshot? Simply pasting in the comment box works.

**Comment by exmateriae** [comment]
I meant the community prediction on the timeline sorry
![Screenshot_20241014_061937_Chrome](https://github.com/user-attachments/assets/688ade59-80a6-41ea-b357-bda0ce81ea16)

**Comment by ncarazon** [comment]
This one looks fixed:

<img width="766" alt="image" src="https://github.com/user-attachments/assets/07348150-fe40-45e5-a55e-5bb55b2b1822">

<img width="779" alt="image" src="https://github.com/user-attachments/assets/7e83fd7c-4d46-421c-8537-8eb787d30c73">

**Comment by SylvainChevalier** [comment]
lgtm
