### ISSUE TITLE
Only start using scientific notation below 0.001

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#990]
## Current behavior
As far as I can tell, all numbers <1 are represented using scientific notation. [Example](https://www.metaculus.com/questions/23762/if-at-least-100-human-cases-of-h5n1-are-confirmed-in-the-united-states-in-2024-what-will-the-estimated-case-fatality-rate-in-percent-be-in-the-us/#comment-199995):
![image](https://github.com/user-attachments/assets/90694160-24a5-4655-bc43-0b37d86d8ddc)

## Expected/desired behavior
Scientific notation should only be used on very small numbers (< 0.0001), imo.

**Comment by SylvainChevalier** [comment]
Let's do <0.001.

**Comment by lsabor** [comment]
done. closing as complete. will be visible at next deployment
