### ISSUE TITLE
API filtering by publish/resolve time not working as expected

### ISSUE THREAD

**Issue by jkraybill** [Metaculus/metaculus#991]
## Current behavior
When I query the API questions feed, and attempt to filter by publish and/or resolve time, I'm getting the full unfiltered questions feed (3917 questions).

A reproducible example of this: https://www.metaculus.com/api2/questions/?include_description=true&published_at__gt=2023-01-01&scheduled_resolve_time__gt=2024-10-14&scheduled_resolve_time__lt=2025-01-01

## Expected/desired behavior
Maybe the URL structure changed, or maybe the parameters are just being ignored. Anyway, the expected behaviour is that the above query only returns questions published and resolving within the queried date ranges.

**Comment by hickman-santini** [comment]
@hlbmtc if this is a URL structure thing, can you respond here and also let Tom know? If it's a bug it's blocking AIB. Thanks!

**Comment by hlbmtc** [comment]
@jkraybill, I've added the two filters to the `/api2/questions` endpoint. The changes will be deployed in ~10 minutes. Could you please confirm this works on your end?

**Comment by jkraybill** [comment]
@hlbmtc yes, working, thanks!
