### ISSUE TITLE
Can't update predictions in question

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#992]
The question in question: https://www.metaculus.com/questions/11419/sota-on-imagenet-top-1-accuracy/
> When reloading the page some time after making my changes and clicking "save change", it seems that my update has not gone through, and the probability distribution is the same as before.

> I’ve had the same problem on the 2024 subquestion. I think this is a problem for all predictors, because that question consistently ranks first when I sort by stale.

**Comment by draaglom** [comment]
Looking at the error message when submitting a forecast on 2024:

```
{"error":"Question 5946 is already closed to forecasting !","message":"$undefined"}
```

it seems the defect is that the UI presents already-closed sub-questions as still open, if there are at least some other sub-questions still open.

**Comment by hlbmtc** [comment]
@draaglom is totally right. This was a frontend bug - https://github.com/Metaculus/metaculus/pull/1014

**Comment by hlbmtc** [comment]
@draaglom is absolutely correct — you shouldn't be able to forecast on this subquestion since it was closed on Oct 14th. This was a frontend bug fixed here - https://github.com/Metaculus/metaculus/pull/1014
