### ISSUE TITLE
Missing API docs

### ISSUE THREAD

**Issue by jkraybill** [Metaculus/metaculus#993]
## Current behavior
The API has had apparently many undocumented changes, and there are currently no docs. The API update post covers some, but not all, and at the moment, if you wanted to join the Q4 AI challenge (for instance), you would have zero API docs to work from. #677 was opened three weeks ago, and cited "in a few weeks".

## Expected/desired behavior
Please expose a doc that at least shows us the schema to expect. I'd actually like to help improve the API docs in the future, but we need a starting point to improve from.

**Comment by SylvainChevalier** [comment]
@jkraybill we have API docs now, at https://www.metaculus.com/api/.
